### ISSUE TITLE
Meterpreter issues with Windows NT 4.0

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#9008] opened 2017-09-26 16:30 UTC
I'm currently experiencing the following issues on a Windows NT 4.0 Machine using Meterpreter (yeah, they still exist):

```
meterpreter > shell
[-] stdapi_fs_file_expand_path: Operation failed: Not enough storage is available to process this command.
meterpreter > ls
[-] stdapi_fs_stat: Operation failed: Not enough storage is available to process this command.
```

Commands like `sysinfo` are working correctly.

Getting a shell with the `execute` command also works (more or less):
```
meterpreter > execute -f cmd.exe -H -i
Process 250 created.
Channel 1 created.
Microsoft(R) Windows NT(TM)
(C) Copyright 1985-1996 Microsoft Corp.

C:\WINNT\system32>
```

Installed version of metasploit-framework on kali: `4.16.8-0kali1`.

Any ideas what could be the problem here?

**Comment by FireFart** [comment] 2017-09-26 17:01
Stacktraces:
```
[09/26/2017 19:00:05] [e(0)] meterpreter: stdapi_fs_stat: Operation failed: Not enough storage is available to process this command.
[09/26/2017 19:00:05] [d(0)] meterpreter: Call stack:
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file_stat.rb:93:in `stat'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file_stat.rb:50:in `initialize'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:184:in `new'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:184:in `stat'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:655:in `cmd_ls'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:195:in `run'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:563:in `_interact'
/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1378:in `cmd_sessions'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
```

```
[09/26/2017 19:00:26] [e(0)] meterpreter: stdapi_fs_file_expand_path: Operation failed: Not enough storage is available to process this command.
[09/26/2017 19:00:26] [d(0)] meterpreter: Call stack:
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:142:in `expand_path'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb:251:in `cmd_shell'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:195:in `run'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:563:in `_interact'
/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1378:in `cmd_sessions'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
```

**Comment by bcoles** [comment] 2017-09-27 02:36
I had a lot of issues with Meterpreter on Windows 98. PHP Meterpreter was the most reliable.

**Comment by sempervictus** [comment] 2017-09-27 15:16
Our compiler target is 120 for XP. This is sort of "expected" but would be nice to fix.
Could you build a debug meterp and pull its dprintf outputs via windbgview or similar? Let's see what the actual payload has to say about this.
How does mettles mingw target fare (there's no stage handler for it, but stageless should work on a stageless handler)?

Ping @OJ: Any way to get vs13 to build pre-xp? Also, how will we handle even 120_XP when we move to VS-next?

**Comment by wwebb-r7** [comment] 2017-10-01 22:28
I did some digging on the same error state in request_fs_stat awhile back for a different command.  I can't recall at the moment what the problem is, though it's fairly obvious I didn't feel it was worth fixing at the time.

I'll update if I still have notes on it.

**Comment by wwebb-r7** [comment] 2017-10-06 08:15
@FireFart - what service pack level is the machine at?

**Comment by FireFart** [comment] 2017-10-06 08:23
It was a german NT4.0 SP4.

I found an ISO at https://archive.org/details/Microsoft_Windows_NT_Workstation_4.0_Microsoft_1996 (serial can be found on google) but this is SP1 and MS removed all service pack downloads from their site :/

**Comment by wwebb-r7** [comment] 2017-10-06 09:11
I had forgotten that the NT 4 source code was leaked, which would certainly speed things up if I were inclined to look at it ..

Basically, you're getting the error from two different commands, each of which makes a different native API call, with the call stack of both ending in two different system calls.  On that alone I'd wager that it's not a Meterpreter issue but rather with the machine itself.  Es ist kaputt.

Mein Deutsch ist schrecklich; however, I think it's probably reproducible on English distros.  My best guess is IRP stack exhaustion, which could be caused by any number of things such as a lot of users being logged on, faulty drivers, or others.

If you still have access and are able to, rebooting the system would probably help.  If you can edit the registry, check out [https://support.microsoft.com/en-us/help/285089/description-of-the-irpstacksize-parameter-in-windows-2000--in-windows](https://support.microsoft.com/en-us/help/285089/description-of-the-irpstacksize-parameter-in-windows-2000--in-windows).  The key should be the same for NT4, but it will also require a reboot.

Also, I could be wrong about all of this.  I'm trying very hard not to install NT 4 at this point.

**Comment by wwebb-r7** [comment] 2017-10-06 09:21
If that's not it, other possible culprits are the paged pool and nonpaged pool.  I have no idea if it's possible to adjust these on NT4.  If so, both would also require a reboot, so it's too bad if that's outside the parameters of your engagement.

**Comment by FireFart** [comment] 2017-10-07 19:05
@wwebb-r7 thanks for the info but as sad as it sounds: It's still a production system so I can't modify these values :/
I think it would be the best to print a warning when establishing a meterpreter session to a host < XP that things may fail because the OS is not supported anymore.

**Comment by wwebb-r7** [comment] 2017-10-07 19:50
I think in this instance I'd blame the nature of the target.  The administrator has basically achieved security through, in all likelihood, having a very busy system and an OS that was notorious for making any kind of meaningful adjustments.

Still, I myself would like to see a legacy branch for Meterpreter.  There are a lot of things that could be done better since the Windows 7 epoch, most of which totally break backwards compatibility.

**Comment by vipzen** [comment] 2017-10-26 00:10
I had the exact same problem with Windows 2000 SP0. See #8333

**Comment by wwebb-r7** [comment] 2017-11-03 19:43
@vipzen see the link I provided.  If that doesn't correct the issue should you encounter it again, well, I'm out of hunches and time to investigate it at the moment.

**Comment by wwebb-r7** [comment] 2017-11-03 19:50
I hope my effort on this helps someone, somewhere ... I'm not planning to revisit it at this point, so closing this.

**Closed by wwebb-r7** 2017-11-03 19:50 UTC

**Comment by vipzen** [comment] 2017-11-03 20:05
@wwebb-r7 I just tried to set the registry value and reboot as indicated, no luck. But I appreciate your effort.

**Comment by wwebb-r7** [comment] 2017-11-03 20:18
I'll keep it in mind in case I'm really bored one weekend.

Is that a freshly booted single user system or something else?

**Comment by vipzen** [comment] 2017-11-03 21:05
Yes, freshly booted VM, single user, no additional third party software, Service Packs or updates.

**Comment by wwebb-r7** [comment] 2017-11-03 21:23
Alright thanks. Again, no promises, but if I do look at it I'll reopen this.

**Comment by vipzen** [comment] 2017-11-06 08:00
FYI, on win2k **SP4** the shell command works fine.

```meterpreter > shell
[-] Failed to spawn shell with thread impersonation. Retrying without it.
Process 412 created.
Channel 2 created.
Microsoft Windows 2000 [Version 5.00.2195]
(C) Copyright 1985-2000 Microsoft Corp

C:\WINNT\sytem32>
