### ISSUE TITLE
Failed to connect to the HTTP data service 

### ISSUE THREAD

**Issue by RaakinShah** [rapid7/metasploit-framework#12840] opened 2020-01-16 14:23 UTC
## Steps to reproduce

1. Installed MSFConsole using the nightly installer with commands 
a. curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

2. cd /opt/metasploit-framework/bin

3 ./msfconsole 

## Expected behavior

Launch without any issues with the connection to the HTTP data service

## Current behavior

Metasploit fails to connect to the HTTP data service but the console still works normally

## Call Stack

Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding

Call stack:
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2067:in `rescue in db_connect_http'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2062:in `db_connect_http'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1832:in `cmd_db_connect'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:252:in `block in load_db_config'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `each_pair'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `load_db_config'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:133:in `initialize'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'

### Metasploit version

5.0.70-dev-5c123e5c1d97fcc5a7e581b465d057d3b6c199c3

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

MacOS Catalina 10.15.1

**Comment by bcoles** [comment] 2020-01-17 12:05
Possible duplicate of #11826 which was never resolved.

**Comment by RaakinShah** [comment] 2020-01-20 21:11
> Possible duplicate of #11826 which was never resolved.

Yeah I looked at that one and saw it wasn't resolved so I wanted to put forward the issue again.

**Comment by ccondon-r7** [comment] 2020-04-12 19:56
Hey @RaakinShah, if this is a duplicate of [#11826](https://github.com/rapid7/metasploit-framework/issues/11826) , it might be better to close the dupe and just comment on the original instead. The sheer number of issues we get on a regular basis (many of which are usage questions and feature requests) makes it time-consuming to triage well, so avoiding duplication wherever possible is helpful!

**Comment by aferrari-arg** [comment] 2020-07-17 03:19
I had the same issue, i could solve it running the follow command in the terminal prompt (not msfconsole):

`msfdb restart`

after that, works perfectly.

**Closed** 2020-07-20 14:26 UTC
Labels: database
