### ISSUE TITLE
[Mac] msfvenom not showing any response

### ISSUE THREAD

**Issue by PeleusGitHub** [rapid7/metasploit-framework#4272] opened 2014-11-27 02:31 UTC
**OS:** OS X 10.10
**Metasploit:** Framework Version: 4.10.1-dev // git pull && bundle install executed just before bug report
**Ruby:** ruby 1.9.3p550 (2014-10-27 revision 48165) [x86_64-darwin14.0.0]

No msfvenom command is performing any visual output or errors, for example: 

msfvenom -h     -> This show's no output
msfvenom -l      -> This show's no output

**dtruss trace**
```
peleus:~/Programs/metasploit$ sudo dtruss -a ./msfvenom -h
	PID/THRD  RELATIVE  ELAPSD    CPU SYSCALL(args) 		 = return
 2642/0x1654d:    110855      49      4 sysctl(0x7FFF565246E8, 0x2, 0x7FFF565246F8)		 = 0 0
 2642/0x1654d:    110861       3      0 thread_selfid(0x7FFF565246E8, 0x2, 0x7FFF565246F8)		 = 91469 0
 2642/0x1654d:    110863       3      1 bsdthread_register(0x7FFF9108F4A4, 0x7FFF9108F494, 0x2000)		 = 1073741855 0
 2642/0x1654d:    110923       5      2 mprotect(0x1096E5000, 0x88, 0x1)		 = 0 0
 2642/0x1654d:    110925       2      0 mprotect(0x1096E7000, 0x1000, 0x0)		 = 0 0
 2642/0x1654d:    110926       2      0 mprotect(0x1096FD000, 0x1000, 0x0)		 = 0 0
 2642/0x1654d:    110938       2      0 mprotect(0x1096FE000, 0x1000, 0x0)		 = 0 0
 2642/0x1654d:    110939       2      0 mprotect(0x109714000, 0x1000, 0x0)		 = 0 0
 2642/0x1654d:    110955       2      0 mprotect(0x109715000, 0x1000, 0x1)		 = 0 0
 2642/0x1654d:    110957       2      1 mprotect(0x1096E5000, 0x88, 0x3)		 = 0 0
 2642/0x1654d:    110968       2      1 mprotect(0x1096E5000, 0x88, 0x1)		 = 0 0
 2642/0x1654d:    110989       2      0 issetugid(0x1096E5000, 0x88, 0x1)		 = 0 0
 2642/0x1654d:    111193       3      0 getpid(0x1096E5000, 0x88, 0x1)		 = 2642 0
 2642/0x1654d:    111199       4      2 stat64("/AppleInternal/XBS/.isChrooted\0", 0x7FFF56524648, 0x1)		 = -1 Err#2
 2642/0x1654d:    111200       2      0 stat64("/BuildSupport/makeProject\0", 0x7FFF56524648, 0x1)		 = -1 Err#2
 2642/0x1654d:    111202       1      0 stat64("/AppleInternal\0", 0x7FFF565245B8, 0x1)		 = -1 Err#2
 2642/0x1654d:    111217       4      1 csops(0xA52, 0x7, 0x7FFF565240E0)		 = 0 0
 2642/0x1654d:    111221       1      0 csops(0xA52, 0x7, 0x7FFF565239C0)		 = 0 0
 2642/0x1654d:       244      47      7 stat64("/usr/lib/libSystem.B.dylib\0", 0x7FFF565240A8, 0x1)		 = 0 0
 2642/0x1654d:       255       4      2 stat64("/usr/lib/system/libcache.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       260       2      1 stat64("/usr/lib/system/libcommonCrypto.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       265       3      1 stat64("/usr/lib/system/libcompiler_rt.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       269       3      1 stat64("/usr/lib/system/libcopyfile.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       273       2      1 stat64("/usr/lib/system/libcorecrypto.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       277       3      1 stat64("/usr/lib/system/libdispatch.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       281       3      1 stat64("/usr/lib/system/libdyld.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       289       3      2 stat64("/usr/lib/system/libkeymgr.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       293       2      1 stat64("/usr/lib/system/liblaunch.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       297       3      1 stat64("/usr/lib/system/libmacho.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       301       2      1 stat64("/usr/lib/system/libquarantine.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       305       2      1 stat64("/usr/lib/system/libremovefile.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       309       2      1 stat64("/usr/lib/system/libsystem_asl.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       313       2      1 stat64("/usr/lib/system/libsystem_blocks.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       316       2      1 stat64("/usr/lib/system/libsystem_c.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       321       2      1 stat64("/usr/lib/system/libsystem_configuration.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       325       2      1 stat64("/usr/lib/system/libsystem_coreservices.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       329       2      1 stat64("/usr/lib/system/libsystem_coretls.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       333       2      1 stat64("/usr/lib/system/libsystem_dnssd.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       337       3      1 stat64("/usr/lib/system/libsystem_info.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       341       2      1 stat64("/usr/lib/system/libsystem_kernel.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       345       2      1 stat64("/usr/lib/system/libsystem_m.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       349       2      1 stat64("/usr/lib/system/libsystem_malloc.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       353       3      2 stat64("/usr/lib/system/libsystem_network.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       358       2      1 stat64("/usr/lib/system/libsystem_networkextension.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       361       2      1 stat64("/usr/lib/system/libsystem_notify.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       367       2      1 stat64("/usr/lib/system/libsystem_platform.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       371       2      1 stat64("/usr/lib/system/libsystem_pthread.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       378       2      1 stat64("/usr/lib/system/libsystem_sandbox.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       382       2      1 stat64("/usr/lib/system/libsystem_secinit.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       387       3      1 stat64("/usr/lib/system/libsystem_stats.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       392       2      1 stat64("/usr/lib/system/libsystem_trace.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       396       2      1 stat64("/usr/lib/system/libunc.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       400       2      1 stat64("/usr/lib/system/libunwind.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       404       2      1 stat64("/usr/lib/system/libxpc.dylib\0", 0x7FFF56523C98, 0x1)		 = 0 0
 2642/0x1654d:       422       2      1 stat64("/usr/lib/libobjc.A.dylib\0", 0x7FFF56522F78, 0x1)		 = 0 0
 2642/0x1654d:       426       2      1 stat64("/usr/lib/libauto.dylib\0", 0x7FFF56522F78, 0x1)		 = 0 0
 2642/0x1654d:       431       2      1 stat64("/usr/lib/libc++abi.dylib\0", 0x7FFF56522E58, 0x1)		 = 0 0
 2642/0x1654d:       435       3      1 stat64("/usr/lib/libc++.1.dylib\0", 0x7FFF56522E58, 0x1)		 = 0 0
 2642/0x1654d:       440       2      1 stat64("/usr/lib/libDiagnosticMessagesClient.dylib\0", 0x7FFF56522D48, 0x1)		 = 0 0
 2642/0x1654d:       515       2      0 getpid(0x7FFF8CF57740, 0x7FFF56522D48, 0x1)		 = 2642 0
 2642/0x1654d:       981      27     21 open("/dev/dtracehelper\0", 0x2, 0x7FFF565250A0)		 = 3 0
 2642/0x1654d:    110724      10      5 close(0x3)		 = 0 0
 2642/0x1654d:    110712  109746 109731 ioctl(0x3, 0x80086804, 0x7FFF56525028)		 = 0 0
 2642/0x1654d:        36      43      0 thread_selfid(0x0, 0x0, 0x0)		 = 91469 0
 2642/0x1654d:    111341      26     21 execve("/Users/peleus/.rvm/gems/ruby-1.9.3-p550@metasploit-framework/bin/ruby\0", 0x7FFF56525B28, 0x7FFF56525B48)		 = -1 Err#2
 2642/0x1654d:    111359      19     17 execve("/Users/peleus/.rvm/gems/ruby-1.9.3-p550@global/bin/ruby\0", 0x7FFF56525B28, 0x7FFF56525B48)		 = -1 Err#2
 2642/0x1654d:        68      42      1 csops(0x0, 0x0, 0x7FFF565251A8)		 = 0 0
 2642/0x1654d:        69       2      0 issetugid(0x0, 0x0, 0x7FFF565251A8)		 = 0 0
 2642/0x1654d:       117       3      1 shared_region_check_np(0x7FFF565230E8, 0x0, 0x7FFF565251A8)		 = 0 0
 2642/0x1654d:       135      17     15 stat64("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x7FFF56524278, 0x7FFF565251A8)		 = 0 0
 2642/0x1654d:       151      15     12 open("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x0, 0x0)		 = 3 0
 2642/0x1654d:       161      14     10 pread(0x3, "\312\376\272\276\0", 0x1000, 0x0)		 = 4096 0
 2642/0x1654d:       164       3      1 pread(0x3, "\317\372\355\376\a\0", 0x1000, 0x1000)		 = 4096 0
 2642/0x1654d:       166       3      1 fcntl(0x3, 0x3D, 0x7FFF565225E0)		 = 0 0
 2642/0x1654d:       177      12      8 mmap(0x1096DF000, 0x2000, 0x5, 0x12, 0x3, 0x1000)		 = 0x1096DF000 0
 2642/0x1654d:       180       4      2 mmap(0x1096E1000, 0x1000, 0x3, 0x12, 0x3, 0x3000)		 = 0x1096E1000 0
 2642/0x1654d:       182       3      1 mmap(0x1096E2000, 0x1FC0, 0x1, 0x12, 0x3, 0x4000)		 = 0x1096E2000 0
 2642/0x1654d:       190       4      2 close(0x3)		 = 0 0
 2642/0x1654d:       193       3      2 stat64("/usr/lib/dtrace/libdtrace_dyld.dylib\0", 0x7FFF56524BF8, 0x1)		 = 0 0

CALL                                        COUNT
bsdthread_register                              1
fcntl                                           1
ioctl                                           1
shared_region_check_np                          1
sysctl                                          1
close                                           2
getpid                                          2
issetugid                                       2
open                                            2
pread                                           2
thread_selfid                                   2
csops                                           3
execve                                          3
mmap                                            3
mprotect                                        8
stat64                                         46

```

**Comment by wchen-r7** [comment] 2015-03-31 04:09
Hi guys, do you still think this is an issue caused by msfvenom? If not can I remove the label? Will keep the issue open.

**Comment by hmoore-r7** [comment] 2015-03-31 04:52
I think this is the same CWD bug w/bundle & binstubs.

**Comment by hmoore-r7** [comment] 2015-03-31 04:53
This may be a dupe of #4602

**Comment by wchen-r7** [comment] 2015-03-31 04:55
That makes sense. Thanks!

**Comment by todb-r7** [comment] 2015-04-13 18:52
Yep, dupe.

**Closed by todb-r7** 2015-04-13 18:52 UTC
Labels: bug
