### ISSUE TITLE
Auxiliary Failed (Win 10)

### ISSUE THREAD

**Issue by Alanay** [rapid7/metasploit-framework#6218] opened 2015-11-10 16:38 UTC
I'm getting this:

Auxiliary failed: Msf::OptionValidateError The following options failed to validate: USER_FILE, PASS_FILE.

When I try to set the USER_FILE/PASS_FILE the backslashes don't appear.

For example:

msf auxiliary(ftp_login) > set USER_FILE C:\Users\HIDDEN\Desktop\top_10.txt
USER_FILE => C:UsersHIDDENDesktoptop_10.txt

Then if I try changing them to forward slashes it still doesn't work. How do I set files using Windows?

**Comment by Alanay** [comment] 2015-11-10 16:57
I added the files to the metasploit folder and just used "set USER_FILE top_10.txt" and that worked.

**Comment by bcook-r7** [comment] 2015-11-10 17:15
use two backslashes

**Comment by Alanay** [comment] 2015-11-10 17:24
@bcool-r7: Thank you

**Comment by wchen-r7** [comment] 2015-11-11 05:57
@Alanay this is the expected behavior, because like @bcook-r7 said you gotta have two backslashes. One slash is technically [character escaping](https://en.wikipedia.org/wiki/Escape_character). I'll go ahead and close this issue, but if you believe this should remain open, please ping us. Thanks.

**Closed by wchen-r7** 2015-11-11 05:57 UTC
