### ISSUE TITLE
Metasploit class names

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#6389] opened 2015-12-22 22:16 UTC
Currently all modules are defined either via `class Metasploit3` or `class Metasploit4`.

```
macbook:metasploit-framework firefart$ grep -ohr "class Metasploit[0-9]" modules/ | sort | uniq -c
2524 class Metasploit3
 167 class Metasploit4
```

Is there any difference between them? If not, can we rename them so all modules use the same class name?
Maybe we could even rename them to only `Metasploit` (without a version number) if there is nothing tied to the number in the name.

Open for discussion

**Comment by jhart-r7** [comment] 2015-12-22 22:34
I don't know that the name matters, but I agree it would be good if they could be consistent.  Seems similar to the problem for #6365 and the solution used in https://github.com/rapid7/metasploit-framework/pull/6388

**Comment by wchen-r7** [comment] 2015-12-22 23:13
I tried once maybe about more than 4 years ago.... I didn't do a very good job, so it was never accepted.

I sort of like the ```Metasploit``` name. That way we don't have to change so many modules every couple of years.

**Comment by FireFart** [comment] 2015-12-22 23:15
btw there is also the `.msf3` and `.msf4` folder in the home directory containing a version number.

**Comment by wvu-r7** [comment] 2015-12-23 04:13
Yes.

**Comment by bcook-r7** [comment] 2015-12-23 09:00
I think the problem this was intended to solve (though I'd call it a failure, unfortunately), is to provide a way for modules to indicate a library API level that they require to run, with the notion that we could change the API for library code and older modules would run unchanged. 'Metasploit3' would somehow represent an unchanging interface, locked in time, while 'Metasploit4' would represent the latest and greatest.

In practice, '3' and '4' are much too coarse, we don't even have a mechanism to show different APIs depending on the inherited class (I think - there could be something subtle :), and since we make small API updates regularly and update the in-tree modules to match along-side these changes, a better analogy would be something like the Linux Kernel driver API - either your module is bundled, or you need to keep up with the latest API at the module level.

If we wanted modules to be able to specify versioning, they'd probably want to specify something finer like 'I need framework API version 4.11.5 or later to run', and since I don't really see anyone with an appetite for maintaining stagnating APIs, it would simply be a flag for whether a module is loadable. That would work if we wanted to implement something like the Linux user-space API; never remove or change an existing API in a backward-incompatible way, only add new ones. I'm not sure we have the will to do that either.

Either way, I think versioning should be in the meta data and be more specific than just major version. I'm with @wchen-r7 in the 'Metasploit' camp.

**Comment by jhart-r7** [comment] 2015-12-23 16:20
+1 on just using `Metasploit`.

**Comment by espreto** [comment] 2015-12-23 17:41
IMHO, +1 ```Metasploit``` :P

**Comment by FireFart** [comment] 2015-12-23 20:12
I found the following code:
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/modules/namespace.rb#L24

which is called by
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/modules/loader/base.rb#L155

So this code also needs a change or be removed

**Comment by FireFart** [comment] 2015-12-28 20:29
@jhart-r7 @bcook-r7 @wvu-r7 @wchen-r7 I tried to remove and adopt some of the loader code in https://github.com/rapid7/metasploit-framework/pull/6405

Would be great if you can have a look because I think this method is not optimal

**Comment by hdm** [comment] 2016-01-05 01:40
The original idea was for modules to have multiple implementations as needed. For example, you could have a Metasploit5 module that also had a Metasploit4 (or 3) implementation. The loader tries to load the current version class first and then walks back to an older version as needed. We never made much use out of it, but its worth thinking about before we change them all to a static value. Given how frequently people try to copy modules from EH/PacketStorm,  a top-level compat indicator would be nice.

**Comment by FireFart** [comment] 2016-01-05 01:55
What do you think of defining a min api version in the modules class initializer so the dev can specify the minimum api version and when the modules api version is below the current one the loader rejects the module? But this would require to change an api version each time a lib/ file is touched. Maybe this can be automated like the github pages rebuild? We would also need a msftidy rule to detect module changes that do not set the api version to the current one.

Another idea would be to gemify the whole lib folder so we have a consistent versioning on each change but I think this is too complicated and too much work.

Anyone has a better idea to fight the copy pasters?

**Comment by wchen-r7** [comment] 2016-05-25 05:44
It looks like this issue should be closed because the idea was implemented and merged in https://github.com/rapid7/metasploit-framework/pull/6655. I should find a place to document @hdm's reason for having different versions though.

**Closed by wchen-r7** 2016-05-25 05:44 UTC
Labels: enhancement, library, module
