### ISSUE TITLE
msf Directly crash after startup

### ISSUE THREAD

**Issue by caidaox** [rapid7/metasploit-framework#19110] opened 2024-04-18 13:20 UTC
<html>
<body>

ruby | 3314 | root | 2024-04-18 21:18:00 | 87.16 %
-- | -- | -- | -- | --

meterpreter > background 
[*] Backgrounding session 5...

Directly crashes after startup, super card

</body>
</html>

**Comment by adfoster-r7** [comment] 2024-04-18 23:54
Potentially a duplicate of https://github.com/rapid7/metasploit-framework/issues/19098

**Closed** 2024-04-20 00:19 UTC
Labels: question
