### ISSUE TITLE
creds_all: NoMethodError undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by friedrico** [rapid7/metasploit-framework#15728] opened 2021-09-30 16:16 UTC
```

creds_all 
[+] Running as SYSTEM
[*] Retrieving all credentials
[-] Error running command creds_all: NoMethodError undefined method `id' for nil:NilClass

```

```
[09/30/2021 12:14:40] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (3)
[09/30/2021 12:14:40] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (3)
[09/30/2021 12:14:40] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (3)
[09/30/2021 12:14:40] [e(0)] meterpreter: Error running command creds_all: NoMethodError undefined method `id' for nil:NilClass
[09/30/2021 12:14:40] [d(0)] meterpreter: Call stack:
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:684:in `report_creds'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:624:in `block (2 levels) in scrape_passwords'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:607:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:607:in `block in scrape_passwords'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:584:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:584:in `scrape_passwords'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:467:in `cmd_creds_all'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:557:in `run_command'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:506:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:500:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:500:in `run_single'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:64:in `block in interact'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:157:in `run'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:62:in `interact'
/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:555:in `_interact'
/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:53:in `interact'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1543:in `cmd_sessions'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:557:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:506:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:500:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:500:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'

```

**Comment by gwillcox-r7** [comment] 2021-10-03 21:15
@friedrico Please use the issue template in future, which requires you to specify the Metasploit version and the Ruby version you are using, along with the steps you took to replicate this issue. As it stands I do not have enough info from this report to replicate your issue as it works fine on my system.

Closing this issue until further information is provided which includes, at a bare minimum, the following pieces of information:

1. OS version of the machine that you ran this again and which latest month of patches installed.
2. Version of Metasploit you are running
3. Version of Ruby you are running.
4. Any nondefault setup on the target machine such as it being a domain connected machine, it being a custom build of Windows, etc, etc.

**Closed** 2021-10-04 02:16 UTC
Labels: bug, needs-issue-template, needs-more-information

**Comment by bcoles** [comment] 2021-10-04 02:27
Looks like a dupe of #15689

**Comment by friedrico** [comment] 2021-10-04 10:29
> Looks like a dupe of #15689

yes, I already forgot that I commented there :joy:

**Comment by friedrico** [comment] 2021-10-04 10:34
```
Framework: 6.1.7-dev
Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

I currently dont have the target information; will supply them when I get my hands on them
