### ISSUE TITLE
execute_dotnet_assemblym The module only supports x64 bit environments

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#19326] opened 2024-07-17 06:21 UTC
The module only supports x64 bit environments
https://www.anquanke.com/post/id/220456
Related source code
The repaired msf execute assemble code is as follows
https://github.com/FunnyWolf/execute-assembl

**Comment by smcintyre-r7** [comment] 2024-07-17 11:33
Closing this as it's a duplicate of a ticket that you yourself opened. See #18334

**Closed by smcintyre-r7** 2024-07-17 11:33 UTC
Labels: bug, suggestion
