### ISSUE TITLE
Cannot display UTF-8 Encoded locale (Russian)

### ISSUE THREAD

**Issue by ext1** [rapid7/metasploit-framework#5574] opened 2015-06-20 12:06 UTC
! if Victim Windows is Russian you will not see folder $U$  

Mode              Size        Type  Last modified              Name
----              ----        ----  -------------              ----
40777/rwxrwxrwx   0           dir   2015-05-16 21:00:42 +0300  $Recycle.Bin
100666/rw-rw-rw-  0           fil   2015-06-20 15:05:00 +0300  $U$  .txt-0xcdeee2fbe920f2e5eaf1f2eee2fbe920e4eeeaf3ece5edf22e747874
40777/rwxrwxrwx   0           dir   2015-06-20 15:04:57 +0300  $U$ -0xcdeee2e0ff20efe0efeae0
100444/r--r--r--  8192        fil   2015-05-16 20:54:55 +0300  BOOTSECT.BAK
40777/rwxrwxrwx   0           dir   2015-05-17 03:46:21 +0300  Boot
40777/rwxrwxrwx   0           dir   2009-07-14 09:08:56 +0400  Documents and Settings
40777/rwxrwxrwx   0           dir   2015-06-17 08:21:24 +0300  ICQ
40777/rwxrwxrwx   0           dir   2009-07-14 07:20:08 +0400  PerfLogs
40555/r-xr-xr-x   0           dir   2015-05-27 12:12:52 +0300  Program Files
40555/r-xr-xr-x   0           dir   2015-06-17 08:20:38 +0300  Program Files (x86)
40777/rwxrwxrwx   0           dir   2015-06-14 11:23:24 +0300  ProgramData
40777/rwxrwxrwx   0           dir   2015-05-16 21:00:15 +0300  Recovery
40777/rwxrwxrwx   0           dir   2015-06-15 07:37:02 +0300  System Volume Information
40555/r-xr-xr-x   0           dir   2015-05-16 21:00:24 +0300  Users
40777/rwxrwxrwx   0           dir   2015-05-23 21:55:07 +0300  Windows
100444/r--r--r--  383786      fil   2010-11-21 06:23:51 +0300  bootmgr
100666/rw-rw-rw-  4294434816  fil   2015-06-20 14:30:35 +0300  pagefile.sys
100666/rw-rw-rw-  312         fil   2015-05-31 14:53:31 +0300  winRAR.reg

![vicproblem](https://cloud.githubusercontent.com/assets/11783361/8267105/67e4b12a-175c-11e5-9ab1-b1c7465f8759.png)

**Comment by bcook-r7** [comment] 2015-06-22 16:40
Can you please provide more information here? Are you using metasploit-framework? What is this screenshot from? Can you please rephrase your issue as a set of steps to reproduce the problem?

**Comment by ext1** [comment] 2015-06-22 18:19
1. Use metasploit-framework + Cobalt Strike like a GUI
2. Use OS Ubuntu Server and Cyborg Hawk  (whith locale "ru_RU.UTF-8")

Victim= Computer: WINDOWS 7 (build 7601, Service Pack 1,  x64 System Language: ru_RU)

problems:
when the meterpreter sessions open and you will try to see folders, all folders, files and other that have name on Russian language will look like " $U$.txt, $U$.exe "

**Comment by bcook-r7** [comment] 2015-06-22 18:24
This may be an issue with the cobalt strike UI not supporting UTF-8 encoding here. Do you still see the issue from a  framework console session?

**Comment by hmoore-r7** [comment] 2015-06-22 18:55
The "$U$ -0xcdeee2e0ff20efe0efeae0" syntax is our built-in unicode encoding when a safe default unicode locale is not detected. It can be disabled using the "disable_unicode_encoding" command.

**Comment by ext1** [comment] 2015-06-22 19:56
when i try to do "disable_unicode_encoding"  in meterpreter, I have see:

40777/rwxrwxrwx   0     dir   2015-06-22 21:12:04 +0300  ����� �����         
40777/rwxrwxrwx   0     dir   2015-06-22 21:12:08 +0300  ����� ����� (2)
40777/rwxrwxrwx   0     dir   2015-06-22 21:12:12 +0300  ����� ����� (3)

**Comment by bcook-r7** [comment] 2015-06-22 19:59
Are you running metasploit under Windows by any chance?

**Comment by ext1** [comment] 2015-06-22 20:00
Use OS Ubuntu Server and Cyborg Hawk (whith locale "ru_RU.UTF-8")

When I use kali-linux - all okey

**Comment by hmoore-r7** [comment] 2015-06-22 20:01
@ext1 Your terminal or GUI needs to be able to display unicode. This isn't a metasploit problem.

**Comment by ext1** [comment] 2015-06-22 20:06
$ locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

**Comment by hmoore-r7** [comment] 2015-06-22 20:14
@ext1 Whatever interface you are using (Cyber Hawk?) is the problem here.

**Comment by ext1** [comment] 2015-06-22 20:15
Problems whith Ubuntu server, and Ubuntu, too

**Comment by hmoore-r7** [comment] 2015-06-22 20:21
@ext1 Unless you can reproduce this with msfconsole, we will close this ticket. The issue is with the application you are using that presents the text.

**Comment by hmoore-r7** [comment] 2015-06-22 20:23
@ext1 Make sure your console has unicode support and that you are using a unicode font.

**Comment by ext1** [comment] 2015-06-22 20:23
Thx I will test all)))

**Comment by jvazquez-r7** [comment] 2015-08-10 21:14
@ext1 were you able to test @hmoore-r7's feedback. If there isn't any update I'll be closing this ticket on Friday.

**Comment by egypt** [comment] 2016-08-24 15:46
Haven't seen any updates here, I'll assume it was a terminal issue.

**Closed by egypt** 2016-08-24 15:46 UTC
Labels: bug
