### ISSUE TITLE
auxiliary/server/tftp  ERROR: Auxiliary failed: option RHOSTS failed to validate.

### ISSUE THREAD

**Issue by jsarkisian** [rapid7/metasploit-framework#11475] opened 2019-02-24 23:25 UTC
Expected behavior: Server starts after setting SRVHOST and executing "run".

Observed behavior: When setting appropriate options (this has always worked in the past) the module errors out with the following after execution:

[-] Auxiliary failed: option RHOSTS failed to validate.

Has something changed since previous MSF version? Not sure why it wants RHOSTS, especially given there is no option to set it in the module.

**Comment by benichmt1** [comment] 2019-02-25 15:50
I can confirm I also have this issue on the latest nightly release

**Comment by bcoles** [comment] 2019-02-25 15:53
Yes, this is a bug. There's several issues posted for it now.

#11480 #11475 #11474 #11448

Perhaps two different bugs both introduced around the same tim. One bug related to `action`, and another related to modules requiring `rhosts` when they don't actually require it.

**Comment by busterb** [comment] 2019-02-25 20:24
Hi, taking a look now. Thanks for the report.

**Comment by busterb** [comment] 2019-02-25 20:48
At first blush, it looks like #11176 might be the root of all things being reported here.

**Comment by busterb** [comment] 2019-02-25 22:32
I found both bugs and think they are resolved in the above PR. Mind giving it a spin?

**Closed** 2019-02-26 15:42 UTC
Labels: bug
