### ISSUE TITLE
stdapi_webcam_start: Operation failed: 1

### ISSUE THREAD

**Issue by ankit383** [rapid7/metasploit-framework#16253] opened 2022-03-01 18:28 UTC
When i use this cmd webcam_snap -i  i am always showing error 
(stdapi_webcam_start: Operation failed: 1 ) why?

**Comment by smcintyre-r7** [comment] 2022-03-15 15:34
Duplicate of #16222.

**Closed by smcintyre-r7** 2022-03-15 15:34 UTC
Labels: bug
