### ISSUE TITLE
meterpreter android commands missing. failed to "load android"

### ISSUE THREAD

**Issue by nbexiga** [rapid7/metasploit-framework#9262] opened 2017-11-30 11:56 UTC
hi,
i have updated kali linux , and now when i enter in the mscsonsole and try to run the ? for get commands i cannot see the android commands like webcam_stream -i  or record_mic -d .
if i run load android i get this error :
Failed to load plugin from /opt/metasploit-framework/embedded/framework/plugins/android: cannot load such file -- /opt/metasploit-framework/embedded/framework/plugins/android

can you please help?
thanks

**Comment by timwr** [comment] 2017-11-30 12:49
The android commands might not be there immediately depending on how fast your connection is, but they should appear eventually. There is no need to run `load android`.
I can't reproduce this.
Can you follow the instructions here: https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/android/meterpreter/reverse_tcp.md ?

**Comment by jmartin-r7** [comment] 2017-11-30 20:57
Also can you validate the prompt you are at `msf>` or `meterpreter>`?  You may have a session but still be at a console prompt.

**Comment by jmartin-r7** [comment] 2017-12-11 22:53
Closing as user context issue. Expect user was either not at a `meterpreter` prompt or the session had not yet loaded fully.

**Closed by jmartin-r7** 2017-12-11 22:53 UTC
