### ISSUE TITLE
stuck after - Started HTTPS reverse handler , please help me 

### ISSUE THREAD

**Issue by SAJJADALIDON** [rapid7/metasploit-framework#9625] opened 2018-02-25 13:08 UTC
please solve this issuse.

![capture2](https://user-images.githubusercontent.com/28814947/36641733-c2dc666c-19e9-11e8-882c-4bd8acba6ec6.PNG)

**Comment by h00die** [comment] 2018-02-25 13:44
Duplicate of #9626

**Closed by h00die** 2018-02-25 13:44 UTC
