### ISSUE TITLE
Add BadPotato

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#13438] opened 2020-05-12 07:11 UTC
https://github.com/BeichenDream/BadPotato
https://github.com/vletoux/pingcastle
https://itm4n.github.io/printspoofer-abusing-impersonate-privileges/

**Comment by bcoles** [comment] 2020-05-12 07:14
Probably a dupe of #13381

**Comment by bcoles** [comment] 2022-01-29 05:03
Closing as dupe of #13381.

**Closed by bcoles** 2022-01-29 05:03 UTC
Labels: suggestion-module
