### ISSUE TITLE
There is a malware in your bug

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16037] opened 2022-01-08 22:33 UTC
Too many attentions over windows/osx platform but mobile devices get ignored as usual
I can't even delete my files on my android sd card from my meterpreter session
OFC

**Comment by czonta96** [comment] 2022-01-09 02:45
In order to delete a file from memory sdcard I have to enter shell, basic meterpreter just says error if I try to do this.
And no options to make keylogging, I can just watch my screen

I'm not pretending that meterpreter should be like pegasus, damn just add basic functions it has on computer devices!

**Comment by h00die** [comment] 2022-01-09 03:03
The great thing about open source software is the ability for anyone to contribute to make it better. Please feel free to submit Pull Requests for peer review with any new or improved functionality.

**Comment by timwr** [comment] 2022-01-11 05:30
@czonta96 I don't suppose you can provide logs/console output of this?
It's strange that it works in `meterpreter > shell` but not meterpreter itself.

**Comment by gwillcox-r7** [comment] 2022-01-19 23:35
Closing issue due to lack of information, not following issue template, and author has opened up other issues on separate questions over the past few days. If more evidence can be provided, we can consider looking into this more but for now there is nothing actionable here to work off of.

**Closed by gwillcox-r7** 2022-01-19 23:35 UTC
Labels: meterpreter, bug, android, suggestion-feature, needs-more-information

**Comment by bcoles** [comment] 2022-03-18 19:43
> @czonta96 I don't suppose you can provide logs/console output of this? It's strange that it works in `meterpreter > shell` but not meterpreter itself.

Strange indeed. I can't reproduce this issue on an emulated Pixel 4 device running Android 11. Upload to `/sdcard` and subsequent delete with `rm` and `del` works.

```
meterpreter > cd /sdcard
meterpreter > pwd
/storage/emulated/0
meterpreter > ls
Listing: /storage/emulated/0
============================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:52 -0500  Alarms
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:45 -0500  Android
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:53 -0500  Audiobooks
040776/rwxrwxrw-  4096  dir   2022-03-15 18:59:26 -0400  DCIM
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:53 -0500  Documents
040776/rwxrwxrw-  4096  dir   2022-03-18 14:53:37 -0400  Download
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:53 -0500  Movies
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:53 -0500  Music
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:52 -0500  Notifications
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:53 -0500  Pictures
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:52 -0500  Podcasts
040776/rwxrwxrw-  4096  dir   2022-01-27 02:51:52 -0500  Ringtones

meterpreter > upload /tmp/test
[*] uploading  : /tmp/test -> test
[*] Uploaded -1.00 B of 21.00 B (-4.76%): /tmp/test -> test
[*] uploaded   : /tmp/test -> test
meterpreter > cat test
#!/bin/sh
echo hello
meterpreter > rm test
meterpreter > cat test
[-] stdapi_fs_stat: Operation failed: 1
meterpreter > upload /tmp/test
[*] uploading  : /tmp/test -> test
[*] Uploaded -1.00 B of 21.00 B (-4.76%): /tmp/test -> test
[*] uploaded   : /tmp/test -> test
meterpreter > cat test
#!/bin/sh
echo hello
meterpreter > del test
meterpreter > cat test
[-] stdapi_fs_stat: Operation failed: 1
meterpreter > 
```
