### ISSUE TITLE
SNMP Login Scanner multiple issues

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#5266] opened 2015-04-28 20:36 UTC
This is the output of the SNMP Login scanner (https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/snmp/snmp_login.rb) in verbose mode without having a DB connected.
Also notice the wrong messages printed out.

* We only need the "no DB active" message once
 * https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/lib/msf/core/auxiliary/report.rb#L43
* The output needs to be changed
 * On fail a `credential.proof` is printed out. It's only non nil on success so the `proof` needs to be moved to the success message: https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/modules/auxiliary/scanner/snmp/snmp_login.rb#L83
 * There is an extra `:` after the credential which looks like it's caused by `.to_s`: https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/lib/metasploit/framework/credential.rb#L79
 * The leading `:161SNMP` tracks down to here: https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/lib/msf/core/auxiliary/auth_brute.rb#L570 The Code assumes there is a `RHOST` datastore option but in this case it's a `RHOSTS`. The rest of the code uses the `RHOST`option multiple times (example: https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/lib/msf/core/auxiliary/auth_brute.rb#L252) so these occurences need to be changed too

```
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: private: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[!] No active DB -- Credential data will not be saved!
[+] 10.10.10.10:161 - LOGIN SUCCESSFUL: 0: (Access level: read-only)
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: 0392a0: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: 1234: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: 2read: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: 4changes: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: ANYCOM: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: Admin: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: C0de: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: CISCO: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: CR52401: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: IBM: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: ILMI: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: Intermec: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: NoGaH$@!: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: OrigEquipMfr: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: PRIVATE: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: PUBLIC: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: Private: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: Public: (Incorrect: )
[!] No active DB -- Credential data will not be saved!
[-] :161SNMP - 10.10.10.10:161 - LOGIN FAILED: SECRET: (Incorrect: )
```

**Comment by wvu-r7** [comment] 2015-04-28 20:55
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/auxiliary/report.rb#L27

**Comment by FireFart** [comment] 2015-04-28 20:56
About the `:161SNMP`:
print_brute assumes there is at least a RHOST datastore option (multiple times in this file), but in this case we have a RHOSTS:
https://github.com/rapid7/metasploit-framework/blob/c2a252face46e541c6608f56abf1945cc91231e8/lib/msf/core/auxiliary/auth_brute.rb#L570

**Comment by FireFart** [comment] 2015-04-28 20:59
@wvu-r7 in this case it's `invalidate_login` :) https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/auxiliary/report.rb#L43

**Comment by wvu-r7** [comment] 2015-04-28 21:22
Err, yeah. This looks messy to refactor.

**Comment by FireFart** [comment] 2015-04-28 21:34
@wvu-r7 I think the extra `:` after the password is caused by this:
https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/credential.rb#L79

So there are multiple bugs to fix in this one, and all of them are more than a change of a single line :(

**Comment by FireFart** [comment] 2015-04-28 21:43
@wvu-r7 i updated the main bug description to collect all information

**Comment by wvu-r7** [comment] 2015-04-28 22:21
I just don't want to break the new creds stuff, lol.

**Comment by Meatballs1** [comment] 2015-05-15 18:09
Maybe get picked up with https://github.com/rapid7/metasploit-framework/issues/4718

**Comment by dmaloney-r7** [comment] 2015-05-15 20:30
rhost as a method is supposed to grab the current ip in scanner modules like that, so that should work. interesting that it isn't. Since that problem is in print_brute that may crop up other places too

**Comment by dmaloney-r7** [comment] 2015-05-15 20:35
Yeah, the AuthBrute mixin is old and predates jthe creds refactor, but it used to be that RHOST would be modified iirc to reflect that thread's current ip. I suspect this has changed recently in sanity fixes to datastore

**Comment by dmaloney-r7** [comment] 2015-05-18 18:31
actually the snmp login scanner module doesn't use print_brute at all

**Comment by dmaloney-r7** [comment] 2015-05-18 18:33
The snmp_login module uses print_good or vprint_error, and uses the ip var yielded by the batch. So I cannot reproduce this issue with the ip being dropped at all. Not sure how you're seeing that.

**Comment by dmaloney-r7** [comment] 2015-05-18 18:35
also, those database warnings only show up if you have VERBOSE set to true

**Comment by dmaloney-r7** [comment] 2015-05-18 18:49
ack, i can repro the ip issue on failures. hrm

**Comment by dmaloney-r7** [comment] 2015-05-18 18:51
it was because it was vrpint_error for some reason which did go through auth_brute. Silly

**Comment by dmaloney-r7** [comment] 2015-05-18 18:53
https://github.com/rapid7/metasploit-framework/pull/5369 should address all of the issues specifically reported in this ticket.

**Comment by dmaloney-r7** [comment] 2015-05-19 16:31
These issues were fixed in https://github.com/rapid7/metasploit-framework/pull/5369

**Closed by dmaloney-r7** 2015-05-19 16:31 UTC
Labels: bug, creds, library, module

**Comment by FireFart** [comment] 2015-05-19 18:09
thx @dmaloney-r7 !!!
