### ISSUE TITLE
Psexec against Win 8.1 Pro - Interactive services error

### ISSUE THREAD

**Issue by splotsh** [rapid7/metasploit-framework#4591] opened 2015-01-15 22:15 UTC
Psexec against a Windows 8.1 pro box (domain joined, using domain creds) results in the following error "The MlAzaJQoawRJFJDczgt service is marked as an interactive service. However, the system is configured to not allow interactive services. This service may not function properly". This test was done from a Win7 system running -  =[ metasploit v4.10.1-2014111001 [core:4.10.1.pre.2014111001 api:1.0.0]] - pro trial

Trying the latest ver of Metasploit (metasploit v4.11.0-dev [core:4.11.0.pre.dev api:1.0.0])  pulled from the repo on Debian against the same target returned a Metasploit error of 225 on the client side, however the event log on Windows showed that a service had been successfully installed. 

Sysinternals Psexec works against the same system without any problems. Can anyone re-produce this ?

**Comment by nidem** [comment] 2015-02-21 01:24
I've had this same problem but in certain installs of Windows 2012. I went back to 4.8 and it worked for me.

**Comment by wchen-r7** [comment] 2015-07-03 05:46
I believe @egypt is working on psexec for newer Windows so I will assign to him.

**Comment by dmaloney-r7** [comment] 2017-08-29 15:44
@nidem @splotsh I know it's been a long time on this ticket, but were you using the Powershell or Native Upload target?

**Comment by dmaloney-r7** [comment] 2017-08-29 16:17
I tested against Win7 and Win2k16 with NoInteractiveServices turned on, and i cannot reproduce this error and get a session, with reverse_tcp and reverse_https.  As this is a 2 year old bug I'm closing this out until and unless someone else comes along and reports it again.

If someone else encounters this problem we may want to look at removing the Interactive Flag from this bit here:

https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/proto/dcerpc/svcctl/packet.rb#L88-L134

**Closed by dmaloney-r7** 2017-08-29 16:17 UTC
Labels: bug, module, rubysmb
