### ISSUE TITLE
MSFCONSOLE -X Multiple Instance Failure

### ISSUE THREAD

**Issue by T-S-A** [rapid7/metasploit-framework#4549] opened 2015-01-07 22:29 UTC
Due to msfcli going away soon, I've started upgrading automation code to use msfconsole -x. This new method has a serious issue that needs to be overcome.

For example, if you run msfconsole -x "use auxiliary/scanner/snmp/snmp_login;set rhosts 127.0.0.1;run;exit -y;" by itself, the msfconsole loads and runs the module fine, but if you try to run that same command three times, causing multiple msfconsole instances to load at the same time, msfconsole will start throwing errors like, "[-] Failed to load module: auxiliary/scanner/snmp/snmp_login" and "[-] Unknown command: run."

With msfcli, I could run 10+ instances at the same time with no problems, but with msfconsole -x, trying to run a few instances at the same time causes serious issues which results in most of the instances failing.

Thanks!

**Comment by todb-r7** [comment] 2015-01-08 16:30
I bet you're hitting #4340. That needs to be resolved before fulling kicking out msfcli, and the sooner the better.

Try this, drop a `sleep 3; use auxiliary...` in the -x and see if that resolves. msfconsole loads significantly faster than msfcli so there's a race in there on module indexing.

**Comment by todb-r7** [comment] 2015-01-08 16:32
If the sleep trick works this is a dupe of #4340 for sure. It's a lame workaround, but I'll close this as a dupe of that if you confirm, @T-S-A .

**Comment by T-S-A** [comment] 2015-01-08 20:26
It seems that your recommendation fixed it. I can run multiple instances of the command below without experiencing the issues mentioned previously. Thanks!

msfconsole -x "sleep 3;use auxiliary/scanner/snmp/snmp_login;set rhosts 127.0.0.1;run;exit -y;"

**Comment by todb-r7** [comment] 2015-01-20 18:26
Okay. I'm going to drop a temp fix in for -x that always drops a leading `sleep` in there. It's lame but it works until the module counting/indexing/caching is solid.

**Comment by todb-r7** [comment] 2015-01-20 21:22
Hah, this is more complicated than expected. I'm trying to induce the behavior, and it's stubbornly avoiding it. I will get into periods where all the modules load fine, then not, then again, and I'm not seeing any obvious differences in framework.log after some instrumentation. It's very streaky and is starting to feel like a Baccarat game.

**Comment by todb-r7** [comment] 2015-01-20 21:27
For example, no changes between runs:

````
todb@mazikeen:~/git/rapid7/metasploit-framework$ ./msfconsole -Lqx "use auxiliary/test/slow_module;exit"
[-] Failed to load module: auxiliary/test/slow_module
[ruby-2.1.5@metasploit-framework](temp) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ ./msfconsole -Lqx "use auxiliary/test/slow_module;exit"
[ruby-2.1.5@metasploit-framework](temp) 
todb@mazikeen:~/git/rapid7/metasploit-framework$
````

I'm going to wrap `cmd_use` with a try-again, I believe.

**Comment by todb-r7** [comment] 2015-01-20 22:11
Hey @T-S-A I have a fix up that seems effective. Hopefully @wvu or @kernelsmith or someone will test and land, or see that the fix is kinda silly and complain about it. :)

**Comment by T-S-A** [comment] 2015-01-20 22:40
Thanks!

**Closed** 2015-01-21 13:40 UTC
Labels: bug, library, msfcli
