### ISSUE TITLE
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil

### ISSUE THREAD

**Issue by Fawniaus** [rapid7/metasploit-framework#13245] opened 2020-04-14 05:59 UTC
## Steps to reproduce

How'd you do it?

1.msfconsole

I just start metasploit or use some module it show up to me like this:
![IMG_20200414_114427](https://user-images.githubusercontent.com/43487032/79190835-734a8080-7e4f-11ea-825c-94bfb853278f.JPG)

### Metasploit version

metasploit v5.0.83-dev

### I installed Metasploit with:
- [ ✓ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
>Android9,Vivo1906

**Comment by bcoles** [comment] 2020-04-14 06:43
Dupe of #13225

It looks like this issue exists in the `activerecord` Ruby gem. Not sure if this affects Metasploit, which specifies Ruby version 2.6.5. This also looks like a warning. Does Metasploit work as intended?

**Comment by Fawniaus** [comment] 2020-04-14 12:51
> Dupe of #13225
> 
> It looks like this issue exists in the `activerecord` Ruby gem. Not sure if this affects Metasploit, which specifies Ruby version 2.6.5. This also looks like a warning. Does Metasploit work as intended?

It just work like everytime but this time it show some warning and nothing fail like just warning,so i need to close it,it too annoying me sir.

**Comment by bcoles** [comment] 2020-04-14 12:52
> 
> 
> > Dupe of #13225
> > It looks like this issue exists in the `activerecord` Ruby gem. Not sure if this affects Metasploit, which specifies Ruby version 2.6.5. This also looks like a warning. Does Metasploit work as intended?
> 
> It just work like everytime but this time it show some warning and nothing fail like just warning,so i need to close it,it too annoying me sir.

You can hide Ruby warnings with `-W0` :

```
ruby -W0 ./msfconsole
```

**Comment by adfoster-r7** [comment] 2020-04-15 11:03
This is a warning created by Ruby 2.7 and activerecord 4.2.11.1 - for more details see https://github.com/rapid7/metasploit-framework/issues/12809

It can safely be ignored for now, and will be fixed in the future.

**Closed by adfoster-r7** 2020-04-15 11:03 UTC
Labels: termux
