### ISSUE TITLE
some modules can not "report_web_vuln"

### ISSUE THREAD

**Issue by leveryd** [rapid7/metasploit-framework#4732] opened 2015-02-08 05:16 UTC
```
msf auxiliary(scraper) > run

[*] [123.125.117.7] / [?..?..?..涓..?.?浣..?..]
[-] Auxiliary failed: NoMethodError undefined method `find_or_initialize_by_web_site_id_and_path_and_method_and_pname_and_name_and_category_and_query' for #<Class:0xc0a6994>
[-] Call stack:
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/dynamic_matchers.rb:27:in `method_missing'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/db_manager/web.rb:345:in `block in report_web_vuln'
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/db_manager/web.rb:283:in `report_web_vuln'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/auxiliary/report.rb:320:in `report_web_vuln'
[-]   /opt/metasploit/apps/pro/msf3/modules/auxiliary/scanner/http/scraper.rb:84:in `block in run_host'
[-]   /opt/metasploit/apps/pro/msf3/modules/auxiliary/scanner/http/scraper.rb:60:in `each'
[-]   /opt/metasploit/apps/pro/msf3/modules/auxiliary/scanner/http/scraper.rb:60:in `run_host'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
msf auxiliary(scraper) > info

       Name: HTTP Page Scraper
     Module: auxiliary/scanner/http/scraper
    License: Metasploit Framework License (BSD)
       Rank: Normal

Provided by:
  et <et@metasploit.com>

Basic options:
  Name     Current Setting                                Required  Description
  ----     ---------------                                --------  -----------
  PATH     /                                              yes       The test path to the page to analize
  PATTERN  <title>(.*)</title>                            yes       The regex to use (default regex is a sample to grab page title)
  Proxies                                                 no        A proxy chain of format type:host:port[,type:host:port][...]
  RHOSTS   file:/tmp/msf-db-rhosts-20150208-7417-1na1iaf  yes       The target address range or CIDR identifier
  RPORT    80                                             yes       The target port
  THREADS  1                                              yes       The number of concurrent threads
  VHOST                                                   no        HTTP server virtual host

Description:
  Scrap defined data from a specific web page based on a regular 
  expresion
```

**Comment by jvazquez-r7** [comment] 2015-02-12 18:57
I cannot reproduce:

```
msf auxiliary(scraper) > workspace -a test_web
[*] Added workspace: test_web
msf auxiliary(scraper) > run

[*] [172.16.158.133] /letterbox/login.php/ [Gestion du courrier]
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

On the database:

```
msf_prod=> select * from web_vulns;
 id | web_site_id |         created_at         |         updated_at         |         path          | method |  params  | pname | risk |  name   | query | category | confidence | description | blame | request |                  proof                   | owner | payload
----+-------------+----------------------------+----------------------------+-----------------------+--------+----------+-------+------+---------+-------+----------+------------+-------------+-------+---------+------------------------------------------+-------+---------
  1 |           6 | 2015-02-12 18:41:48.065635 | 2015-02-12 18:41:48.065635 | /                     | GET    | BAhbAA==+|       |    0 | scraper |       | scraper  |        100 | Scraper     |       |         | \x496e646578206f66202f                   |       |
    |             |                            |                            |                       |        |          |       |      |         |       |          |            |             |       |         |                                          |       |
  2 |           6 | 2015-02-12 18:43:00.836102 | 2015-02-12 18:43:00.836102 | /letterbox/login.php/ | GET    | BAhbAA==+|       |    0 | scraper |       | scraper  |        100 | Scraper     |       |         | \x47657374696f6e20647520636f757272696572 |       |
    |             |                            |                            |                       |        |          |       |      |         |       |          |            |             |       |         |                                          |       |
  3 |           7 | 2015-02-12 18:45:25.159338 | 2015-02-12 18:45:25.159338 | /letterbox/login.php/ | GET    | BAhbAA==+|       |    0 | scraper |       | scraper  |        100 | Scraper     |       |         | \x47657374696f6e20647520636f757272696572 |       |
    |             |                            |                            |                       |        |          |       |      |         |       |          |            |             |       |         |                                          |       |
```

@leveryd do you mind to verify which you're working with an up to date framework and your database is ok?

If you're on a development environment, and you would like to "reinstall" your database you can do:

**WARNING: You're going to drop your current database, so don't it unless your database is just a development one whose data you don't mind to lose***

```
rake db::drop
rake db::create
rake db::migrate
```

**Comment by hmoore-r7** [comment] 2015-02-22 20:47
@leveryd ping

**Comment by leveryd** [comment] 2015-02-24 03:04
ubuntu@VM-131-71-ubuntu:~$ msfconsole -v
Framework Version: 4.11.0-2015013101

i download the stable version on linux,and the problem still exsists

**Comment by hmoore-r7** [comment] 2015-02-24 03:43
Please try after applying the latest update.

**Comment by hmoore-r7** [comment] 2015-02-24 03:46
The version you are testing is not running the latest update. Testing with the latest and the site specified, I can't reproduce this on master:
```
> use auxiliary/scanner/http/scraper 
msf auxiliary(scraper) > set RHOSTS 123.125.117.7
RHOSTS => 123.125.117.7
msf auxiliary(scraper) > run

[*] [123.125.117.7] / [玛莎拉蒂│让世界听见你的呐喊]
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by wchen-r7** [comment] 2015-02-24 04:44
Yeah if you're on framework the module works fine. This is the same issue as:
https://github.com/rapid7/metasploit-framework/issues/3952

**Comment by wchen-r7** [comment] 2015-02-24 04:46
Oh, actually #3952 and #4732 are different modules. Same type of error though.

**Comment by wchen-r7** [comment] 2015-07-03 05:12
I can no longer reproduce this problem. It might have been an old caching problem, but as long as you're using the latest everything (and a clean database just in case), it should be working again:

![screen shot 2015-07-03 at 12 11 20 am](https://cloud.githubusercontent.com/assets/1170914/8492944/167fd600-2118-11e5-821c-9f3958a2526e.png)

I will go ahead and close this issue. If you'd like to reopen, please let us know. Thanks.

**Closed by wchen-r7** 2015-07-03 05:12 UTC
Labels: bug, library
