### ISSUE TITLE
x64 NOP Generator Problem with badchars variable loop in generate_sled() of simple.rb

### ISSUE THREAD

**Issue by jsthyer** [rapid7/metasploit-framework#5846] opened 2015-08-14 15:45 UTC
$ msfvenom -p windows/x64/meterpreter/reverse_tcp -n 128 -f pythonNo platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86_64 from the payload
No encoder or badchars specified, outputting raw payload
undefined method `each' for "":String

LINE 221 ---> this loop needs to be contained within an "IF" statement or similar to check if the badchars variable is a NUL string or not.

      badchars.each do | bc |
        if instruction[I_OP].include?( bc )
          good = false
          break
        end
      end

**Comment by jvazquez-r7** [comment] 2015-08-17 16:19
Hello @jsthyer, thanks for your report. I could successfully reproduce the problem but I think it isn't due to bachars not being initialized. It is correctly initialized really. The problem it trying to iterate over the string with `#each`. Since `badchars` is an string `#each_char` should be used instead. A patch is available here: https://github.com/rapid7/metasploit-framework/pull/5856 Feel free to test it and let us know if it fixes the issue for you. Thanks!

**Comment by jsthyer** [comment] 2015-08-17 16:24
Yes, I put the request in fairly quickly.   It is definitely the "each"
loop that is the problem.   Thanks for looking at it.

**Comment by jlee-r7** [comment] 2015-08-17 21:45
Fixed in #5856

**Closed by jlee-r7** 2015-08-17 21:45 UTC
Labels: bug, module, msfvenom
