### ISSUE TITLE
Error Run Win 11 x 64

### ISSUE THREAD

**Issue by lolminerxmrig** [rapid7/metasploit-framework#19532] opened 2024-10-06 09:39 UTC
Hi all.
last v download.
plz help fixed Error : 

![image](https://github.com/user-attachments/assets/695202ec-69a2-440b-87d3-79819d687109)

**Comment by szymonj99** [comment] 2024-10-06 14:13
https://github.com/rapid7/metasploit-framework/issues/19530#issuecomment-2395270801

**Comment by adfoster-r7** [comment] 2024-10-07 20:39
Thanks for raising an issue; Closing as a dupe of #19530

**Closed by adfoster-r7** 2024-10-07 20:39 UTC
Labels: question
