### ISSUE TITLE
Line-endings issues for cross-platform text files set for RHOSTS input

### ISSUE THREAD

**Issue by maaaaz** [rapid7/metasploit-framework#3996] opened 2014-10-10 20:53 UTC
It seems that metasploit only accepts UNIX line-endings style (LF) for the `RHOSTS` option (set like `set RHOSTS file://my/local/file`).

A target file built from a Windows (CR/LF) text processing utility will then lead to the following error: `Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.`

It would be great whether metasploit could automatically strip line-endings according to both conventions.

Cheers.

**Comment by jvazquez-r7** [comment] 2015-05-11 17:06
I'm unable to reproduce on a Windows 7 SP1 32 bits machine using the latest installer (community edition) here: 

https://github.com/rapid7/metasploit-framework/wiki/Downloads-by-Version  
metasploit-4.11.1-windows-installer.exe

The installer comes with Ruby 2.1.5:

```
>> RUBY_VERSION
=> "2.1.5"
```

* With unix files (just new line separators):

```
$ hexdump -C /tmp/test.txt
00000000  31 32 37 2e 30 2e 30 2e  31 0a 31 37 32 2e 31 36  |127.0.0.1.172.16|
00000010  2e 31 35 38 2e 31 0a                              |.158.1.|
00000017
```

From the metasploit pro console:

```
> use auxiliary/scanner/afp/afp_login
msf auxiliary(afp_login) > set RHOSTS file:c:\\test.txt
RHOSTS => file:c:\test.txt
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
```

* With Windows file ("crlf" separators):

```
$ hexdump -C /tmp/windows.txt
00000000  31 32 37 2e 30 2e 30 2e  31 0d 0a 31 37 32 2e 31  |127.0.0.1..172.1|
00000010  36 2e 31 35 38 2e 31                              |6.158.1|
00000017
```
From the metasploit pro console

```
msf auxiliary(afp_login) > set RHOSTS file:c:\\windows.txt
RHOSTS => file:c:\windows.txt
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
```

* My framework environment on OSx (up to date with rapid7/master) also handles both files correctly:

```
msf auxiliary(indusoft_ntwebserver_fileaccess) > use auxiliary/scanner/afp/afp_login
msf auxiliary(afp_login) > set rhosts file:/tmp/test.txt
rhosts => file:/tmp/test.txt
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(afp_login) > set rhosts file:/tmp/windows.txt
rhosts => file:/tmp/windows.txt
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
```

* A linux machine with an up to date metasploit-framework also handles both files correctly:

```
msf > use auxiliary/scanner/afp/afp_login 
tmsf auxiliary(afp_login) > set RHOSTS file:/tmp/test.txt
RHOSTS => file:/tmp/test.txt
msf auxiliary(afp_login) > set verbose true
verbose => true
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(afp_login) > set RHOSTS file:/tmp/windows.txt
RHOSTS => file:/tmp/windows.txt
msf auxiliary(afp_login) > run

[*] Scanning IP: 127.0.0.1
[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanning IP: 172.16.158.1
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed

```

@maaaaz I'm closing this issue at the moment because I'm unable to reproduce. If you're experiencing the issue still feel free to open a new issue with detailed steps (and example files) to reproduce. Thanks!

**Closed by jvazquez-r7** 2015-05-11 17:06 UTC
Labels: bug, library
