### ISSUE TITLE
stdapi_webcam_start: Operation failed: 1

### ISSUE THREAD

**Issue by MURSHIG** [rapid7/metasploit-framework#16222] opened 2022-02-24 18:10 UTC
My payload is android/meterpreter/reverse_tcp;
When I trying exec webcam_snap 1 on the Android under 6, it running normal and taking pic
But when android version is higher than 6 - webcam, activity_start and app_run not working

**Comment by bcoles** [comment] 2022-03-18 19:10
Issue #16313 is a dupe of this issue. Both issues discuss the same commands.

This issue was create first, but closing this issue as #16313 contains additional information.

**Closed by bcoles** 2022-03-18 19:10 UTC
Labels: bug, android

**Comment by ayush169** [comment] 2024-12-31 09:10
I am having the same issue.
