### ISSUE TITLE
msfvenom command not returning anything in window 10. 

### ISSUE THREAD

**Issue by Vikrantojha** [rapid7/metasploit-framework#13237] opened 2020-04-12 17:17 UTC
## I have install Metasploit  latest in window 10. after succesful installation, when i am trying to open metasploit console, its opening with below warning: 
**************************************************************
[*] Starting Metasploit Console...
[-] WARNING! The following modules could not be loaded!
[-]     C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.82/modules/payloads/singles/cmd/unix/reverse_ssh.rb
[-] Please see C:/Users/Vikrant ojha/.msf4/logs/framework.log for details.
***************************************************************************************
when i am checking in log file, i got some dependency not  supported error:
[04/12/2020 21:51:24] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[04/12/2020 21:51:24] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[04/12/2020 21:51:25] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[04/12/2020 21:51:25] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[04/12/2020 21:53:39] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[04/12/2020 21:53:39] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[04/12/2020 21:53:39] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[04/12/2020 21:53:39] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported

**********************************************************************************
When i am trying to execute the command on console, not getting anything
1. Open Metasploit console 
2. type any command with msfvenom 
3. i am always getting result as: [*] exec: msfvenom

NOTE: 
System : window 10 64 bit
metasploit Version:  metasploit v5.0.82-dev
![Error_1](https://user-images.githubusercontent.com/24223309/79075239-39726080-7d0f-11ea-9f35-1e81039ca938.png)
  @@![Error_2_post_execution](https://user-images.githubusercontent.com/24223309/79075241-3d9e7e00-7d0f-11ea-98e4-bf45db5555fc.png)

**Comment by gwillcox-r7** [comment] 2020-04-12 19:15
@Vikrantojha This is expected behavior as you are outputting the results of `msfvenom` to a file located at `C:\Users\Vikrant ojha\Downloads\Testing.apk`. Check to see whether or not this file exists on your system. Additionally `msfvenom` should be run from a standard command line, you do not need to run it inside of `msfconsole` for it to work. Running commands from within `msfconsole` may result in unusual results due to how I/O is handled.

**Comment by gwillcox-r7** [comment] 2020-04-12 19:21
Closing as issue is not formatted in the standard format and this is not an expected use case. Also closing as author appears to be using Metasploit Pro, and we do not handle support for Metasploit Pro. All Metasploit Pro related questions should go through the Rapid7 support channels, which are listed at https://www.rapid7.com/for-customers/

**Closed by gwillcox-r7** 2020-04-12 19:21 UTC
