### ISSUE TITLE
db_export stack trace

### ISSUE THREAD

**Issue by 3041126** [rapid7/metasploit-framework#7010] opened 2016-06-22 20:14 UTC
## Steps to reproduce

db_export -f xml -a test-vm/metasploit.xml
[*] Starting export of workspace test-vm to test-vm/metasploit.xml [ xml ]...
[*]     >> Starting export of report
[-] Error while running command db_export: Couldn't find all Mdm::Notes with 'id': (first, {:conditions=>{:ntype=>"pro.system.compromise"}}) [WHERE "notes"."host_id" = ?] (found 0 results, but was looking for 2)

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:467:in `find_some'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:71:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:99:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:141:in `find'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:128:in `block in extract_host_entries'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:127:in `extract_host_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:115:in `extract_target_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:48:in `to_xml_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1804:in `block in cmd_db_export'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1771:in `cmd_db_export'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:472:in `load_resource'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:226:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:225:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:225:in `initialize'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

### Metasploit version
metasploit v4.12.7-dev 

### I installed Metasploit with:
Kali Linux package via apt

### OS
Kali Linux rolling edition

**Comment by void-in** [comment] 2016-06-23 04:11
This is the duplicate of https://github.com/rapid7/metasploit-framework/issues/7008. Since that one was posted earlier, I am going to close this one. You can follow the progress there. Thanks for reporting.

**Closed by void-in** 2016-06-23 04:11 UTC
