### ISSUE TITLE
Can't open msfconsole

### ISSUE THREAD

**Issue by rkmsh** [rapid7/metasploit-framework#12282] opened 2019-09-06 02:52 UTC
root@kali:~# msfconsole
Ignoring msgpack-1.3.1 because its extensions are not built. Try: gem pristine msgpack --version 1.3.1
Ignoring msgpack-1.3.0 because its extensions are not built. Try: gem pristine msgpack --version 1.3.0
Ignoring network_interface-0.0.2 because its extensions are not built. Try: gem pristine network_interface --version 0.0.2
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring pcaprub-0.13.0 because its extensions are not built. Try: gem pristine pcaprub --version 0.13.0
Ignoring pg-0.21.0 because its extensions are not built. Try: gem pristine pg --version 0.21.0
Ignoring pg_array_parser-0.0.9 because its extensions are not built. Try: gem pristine pg_array_parser --version 0.0.9
Ignoring redcarpet-3.5.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.5.0
Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0
Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
Ignoring thin-1.7.2 because its extensions are not built. Try: gem pristine thin --version 1.7.2
[*] Bundler failed to load and returned this error:

   'cannot load such file -- molinillo'

[*] You may need to uninstall or upgrade bundler

**Comment by busterb** [comment] 2019-09-07 04:20
Metasploit packages on Kali Linux are maintained locally, but this does not look like a likely error that would occur with a default installation. I suspect that you may have manually installed assorted Ruby gems into the system, is this true? You may need to consult the Kali help forums to determine the root cause here.

**Comment by rkmsh** [comment] 2019-09-07 04:53
Yes! I installed Ruby gems for Rails. Any way to resolve this? I tried with bundle reinstall and bundler too, but nothing worked.

**Comment by jmartin-r7** [comment] 2019-10-07 21:44
The simplest method may be to get the list of system gem installed and remove any referenced in startup errors until the install stops complaining, on the other hand most time Kali test systems if VMs are disposable enough to simply export the database and start in a new VM.

Closing this as user env issue and not a metasploit-framework issue.

**Closed by jmartin-r7** 2019-10-07 21:44 UTC
Labels: question
