### ISSUE TITLE
Nodejs Meterpreter

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#14115] opened 2020-09-10 01:12 UTC
I just want to revive this issue #9494

**Comment by GetRektBoy724** [comment] 2020-09-10 01:15
ping : @timwr @bcoles @wchen-r7 @wvu-r7 @itsmeroy2012

**Comment by OJ** [comment] 2020-09-10 01:21
Duplicate of #9494

**Closed by OJ** 2020-09-10 01:21 UTC
Labels: suggestion-feature

**Comment by GetRektBoy724** [comment] 2020-09-10 01:41
hey @OJ Do you know "Revive"??
