### ISSUE TITLE
Metasploit displaying errors with 'getsystem' command

### ISSUE THREAD

**Issue by init5-SF** [rapid7/metasploit-framework#17605] opened 2023-02-06 19:58 UTC
## Steps to reproduce

How'd you do it?

1. Got elevated meterpreter session
2. used the 'getsystem' command

(It worked and I got system, but with a lot of errors)

## Expected behavior

Should get system privs without showing any errors

### Metasploit version

Framework: 6.3.0-dev
Console  : 6.3.0-dev

## Additional Information
Errors:

```
meterpreter > getsystem 
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:998: warning: Exception in finalizer #<Proc:0x00007f63bc7e3db8 /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:339>
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:147:in `synchronize': can't be called from trap context (ThreadError)
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:147:in `send_packet'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:220:in `send_packet_wait_response'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:176:in `send_request'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:362:in `close'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:339:in `block in finalize'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:998:in `chr'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:998:in `block in xor_bytes'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:997:in `each_byte'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:997:in `xor_bytes'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:952:in `to_r'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:137:in `send_packet'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:220:in `send_packet_wait_response'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:176:in `send_request'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/priv/priv.rb:98:in `getsystem'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb:113:in `cmd_getsystem'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:102:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:64:in `block in interact'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:157:in `run'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:62:in `interact'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:565:in `_interact'
	from /usr/share/metasploit-framework/lib/rex/ui/interactive.rb:53:in `interact'
	from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1682:in `cmd_sessions'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:23:in `<main>'
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter >
```

**Comment by adfoster-r7** [comment] 2023-02-06 22:11
Closing as a duplicate of #17593

**Closed by adfoster-r7** 2023-02-06 22:11 UTC
Labels: bug
