### ISSUE TITLE
stream closed in another thread (IOError) msfconsole

### ISSUE THREAD

**Issue by cyph3rsec** [rapid7/metasploit-framework#18482] opened 2023-10-24 19:42 UTC
Hi everyone! Someone else facing the same problem?

```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': stream closed in another thread (IOError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/lib/ruby/vendor_ruby/pry/syntax_highlighter.rb:23:in `overwrite_coderay_comment_token!'
        from /usr/lib/ruby/vendor_ruby/pry/color_printer.rb:9:in `<class:ColorPrinter>'
        from /usr/lib/ruby/vendor_ruby/pry/color_printer.rb:8:in `<class:Pry>'
        from /usr/lib/ruby/vendor_ruby/pry/color_printer.rb:6:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/lib/ruby/vendor_ruby/pry.rb:28:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:126:in `run'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /usr/bin/msfconsole:23:in `<main>'
```

This happened after updating kali-linux.

**Comment by adfoster-r7** [comment] 2023-10-25 00:20
Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/18462

**Closed by adfoster-r7** 2023-10-25 00:20 UTC
Labels: bug, needs-more-information

**Comment by leaglcivilian** [comment] 2023-11-21 16:27
I  encounter an issue as same sa you
![Uploading Snipaste_2023-11-22_00-26-41.png…]()

**Comment by Vin-2018** [comment] 2024-01-27 15:05
> I have encountered the same problem as you. msfconsole also made an error after updating. After searching everywhere, I finally found a solution. That is to type the [msfdb init] command into the terminal. Remember to enter this command with root permission. `msfdb init` only this can be solve the IOError problem

>>I had similar error using a Kali 2023.4 Live USB and this command fixed the issue.  I had to run the command as root:
#msfdb init
#msfconsole
 
Thanks so much guys, fantastic support.
