### ISSUE TITLE
Unable to load office365userenum.py

### ISSUE THREAD

**Issue by 26chk** [rapid7/metasploit-framework#15093] opened 2021-04-23 17:22 UTC
Metasploit Version：metasploit v6.0.42-dev-dc8113fc43

The following message appears after msfconsole starts：

[!] The following modules could not be loaded!..-
[!]     /data/data/com.termux/files/home/Metasploit/modules/auxiliary/gather/office365userenum.py
[!] Please see /data/data/com.termux/files/home/.msf4/logs/framework.log for details.

![Screenshot_20210424_012110](https://user-images.githubusercontent.com/61009000/115907516-931d7700-a49b-11eb-9b0d-3d6c3bdb4a63.jpg)

**Comment by adfoster-r7** [comment] 2021-04-23 19:05
Thanks for raising an issue! Thankfully this is just a warning and can safely be ignored! :+1:
If you want to run this module, you will most likely need to install python and the required dependencies on your environment

I'll close this issue for now as it's a duplicate of https://github.com/rapid7/metasploit-framework/issues/14705 - feel free to reach out if you're still having issues

**Closed by adfoster-r7** 2021-04-23 19:05 UTC
Labels: bug
