### ISSUE TITLE
Unable to rebuild apk with apktool 

### ISSUE THREAD

**Issue by RahulTarafder** [rapid7/metasploit-framework#18977] opened 2024-03-20 05:03 UTC
![Screenshot_2024_0320_102924](https://github.com/rapid7/metasploit-framework/assets/109901628/1025b231-23db-4068-8914-1d5690adfded)

**Comment by bcoles** [comment] 2024-03-20 06:11
Dupe of #18976

**Closed by bcoles** 2024-03-20 06:11 UTC
Labels: question
