### ISSUE TITLE
msfrpcd console failure caused by rex-core upgrade

### ISSUE THREAD

**Issue by NathanZaldivar** [rapid7/metasploit-framework#16802] opened 2022-07-21 14:33 UTC
Just a bump for issue #16580 since its not getting addressed.  Can the rex core downgrade be merged? This is making the RPC server unusable.

https://github.com/rapid7/metasploit-framework/issues/16580

**Comment by bcoles** [comment] 2022-07-21 14:39
> Just a bump for issue https://github.com/rapid7/metasploit-framework/issues/16580 since its not getting addressed.

I've added `not-stale` label to #16580.

> Can the rex core downgrade be merged?

I don't see any PRs or branches for this.

**Comment by NathanZaldivar** [comment] 2022-07-22 14:41
Pull request #16812 made.

I'm not familiar with ruby so I don't know how this will affect things. From my knowledge after changing rex-core versions in the Gemfile.lock you run "bundle install" to apply the changes but the issue is the executables in /bin seem to stop working and the only way to launch any of the Metasploit applications is manually through the /embedded directory.

**Comment by bcoles** [comment] 2022-07-23 06:57
> I'm not familiar with ruby so I don't know how this will affect things. From my knowledge after changing rex-core versions in the Gemfile.lock you run "bundle install" to apply the changes but the issue is the executables in /bin seem to stop working and the only way to launch any of the Metasploit applications is manually through the /embedded directory.

Yeah patching `Gemfile.lock` is the correct approach, but you're likely to run into dependency version conflicts with other gems which depend on the now-updated version.

Updates to the `rex-core` package fixed bugs, so I'm not sure that reverting the library is the best approach. The best, and most time consuming approach, is to determine and patch the root cause of the issue.

Ideally tests should also be added to ensure this issue does not reoccur.

> Pull request #16812 made.

Closing this issue as a dupe of #16580 and in favor of discussion in #16812.

**Closed** 2022-07-23 06:57 UTC
Labels: bug
