### ISSUE TITLE
hey actually i am anew user of metasploit and using windows 11os system 

### ISSUE THREAD

**Issue by ViperGT** [rapid7/metasploit-framework#16148] opened 2022-02-05 11:51 UTC
hey there i am a new user of metasploit and currently running windows 11os i created an android payload it was created and i sent it my android using usb cable after installing it when i clicked it my run command in msfconsole didn't gave any information and stuck after the run command

**Comment by gwillcox-r7** [comment] 2022-02-10 01:55
There is not enough info here to replicate this issue or understand what the issue is about. Please use the template when creating issues and make sure that you fill in the appropriate details as per the questions that are asked there.

Closing as template questions were not answered and as thus it is not possible to replicate this issue.

**Closed by gwillcox-r7** 2022-02-10 01:55 UTC
Labels: question, needs-more-information
