### ISSUE TITLE
MsfConsole Doesnt Start. 

### ISSUE THREAD

**Issue by S1m1B1lly** [rapid7/metasploit-framework#14105] opened 2020-09-08 11:50 UTC
After installing Metasploit i Opened a Terminal (CMD) And 
i wrote `cd C:\metasploit-framework\bin` (C:\metasploit-framework does nothing) then i run `msfconsole` 
and i couldnt start. i tried reinstalling multiple times and it still not work.
The Output i got was `Could not find bcrypt-3.1.15 in any of the sources
Run `bundle install` to install missing gems.`
i did the `bundle install` but it doesnt exist.
I need someone to tell me how do i fix this issue.

 **I am a beginner so tell the most clear way possible.**

Im sorry for my english if i didnt type it well. I am actually Portuguese.

**Comment by kertis8763** [comment] 2020-09-10 14:43
> 
> 
> After installing Metasploit i Opened a Terminal (CMD) And
> i wrote `cd C:\metasploit-framework\bin` (C:\metasploit-framework does nothing) then i run `msfconsole`
> and i couldnt start. i tried reinstalling multiple times and it still not work.
> The Output i got was `Could not find bcrypt-3.1.15 in any of the sources Run `bundle install` to install missing gems.`
> i did the `bundle install` but it doesnt exist.
> I need someone to tell me how do i fix this issue.
> 
> **I am a beginner so tell the most clear way possible.**
> 
> Im sorry for my english if i didnt type it well. I am actually Portuguese.

Going the C way:\metasploit-framework\embedded\Gemfile.lock next, open this file using a text editor and search for the line brypt (3.1.15) change to brypt (3.1.16) Profit

**Comment by franferrax** [comment] 2020-09-10 17:15
Hi, I think this is a duplicate of what I reported in #14101

**Comment by georgemaret** [comment] 2020-09-10 17:33
Are you using windows?
Many windows user have reported this earlier I guess.

**Comment by franferrax** [comment] 2020-09-11 03:36
> Are you using windows?

Yes

> Many windows user have reported this earlier I guess.

I didn't know it was a known/recurrent issue, I wasn't reproducing it with `metasploit-framework-6.0.4` and I only found #13933 & #13894 while searching through the issues before reporting it.

**Comment by acammack-r7** [comment] 2020-09-14 15:41
This also looks to me like a duplicate that is fixed in the latest nightly windows installer. Thanks for the report!

**Closed by acammack-r7** 2020-09-14 15:41 UTC
Labels: bug
