### ISSUE TITLE
Error while running command services: comparison of Array with Array failed

### ISSUE THREAD

**Issue by str4n63r** [rapid7/metasploit-framework#7988] opened 2017-02-22 13:42 UTC
Hello,

I tried using Shodan API through Metasploit and enabled database storage of results as well while using this auxiliary module. But after running the **auxiliary/gather/shodan_search** when I tried "services" to identify the results Metasploit throwed me below error instead search results. 

## Current behavior
[-] Error while running command services: comparison of Array with Array failed

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-text-0.2.11/lib/rex/text/table.rb:195:in `sort!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-text-0.2.11/lib/rex/text/table.rb:195:in `sort_rows'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-text-0.2.11/lib/rex/text/table.rb:110:in `to_s'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:729:in `block in cmd_services'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:560:in `cmd_services'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

**Metasploit version:** metasploit v4.13.22-dev
**OS:** Kali Linux 2016 R2

**Comment by rwhitcroft** [comment] 2017-02-25 02:33
I can't reproduce this. After running the module, `services` shows a bunch of results.

Can you please paste the output of `show options`, `show advanced`, and the output you get when you `run` the module?

**Comment by str4n63r** [comment] 2017-02-25 14:51
@rwhitcroft Below is the output of **show options** for Shodan search auxiliary.

msf auxiliary(shodan_search) > show options 

Module options (auxiliary/gather/shodan_search):

   Name                Current Setting  Required  Description
   ----           ---------------  --------  -----------
   DATABASE                  true             no        Add search results to the database
   MAXPAGE                   100              yes       Max amount of pages to collect
   OUTFILE                      out.txt                       no        A filename to store the list of IPs
   Proxies                                                no        A proxy chain of format type:host:port[,type:host:port][...]
   QUERY                    apache tomcat              yes       Keywords you want to search for
   REGEX                            .*                             yes       Regex search for a specific IP/City/Country/Hostname
   SHODAN_APIKEY      (my_api_key)               yes       The SHODAN API key
   SSL                                 false                        no        Negotiate SSL/TLS for outgoing connections

**Comment by str4n63r** [comment] 2017-02-25 14:53
@rwhitcroft  Below is the output of show options while executing Shodan search auxiliary.

**Output Link:** http://pastebin.com/7SdqEpr1

**Comment by rwhitcroft** [comment] 2017-02-25 22:22
I'm seeing the error now, thanks.

**Comment by rwhitcroft** [comment] 2017-02-26 03:09
This is happening when Ruby tries to sort the table by IP address and can't handle a mix of IPv4 and IPv6.

**Comment by str4n63r** [comment] 2017-02-26 09:47
@rwhitcroft Is there anyway that I can filter out only IPv4 addresses while using this auxiliary module?

**Comment by rwhitcroft** [comment] 2017-02-27 01:01
Not really. Even specifying a negative regex doesn't work because of how the logic is written. You can try setting the pages to 1, clearing out the database with `hosts -d`, re-running the module, and crossing your fingers you don't get an IPv6 address in the results. You can also try running `services` with the `-S` flag to try to pick out entries that also don't contain IPv6 addresses.

It might help if you describe what you're trying to accomplish.

**Comment by busterb** [comment] 2017-02-27 17:27
Bumped gem in #8024, this will be fixed in the next release. Thanks all!

**Closed by busterb** 2017-02-27 17:27 UTC
