### ISSUE TITLE
NoMethodError undefined method `migrated'

### ISSUE THREAD

**Issue by Mrlaminat** [rapid7/metasploit-framework#12128] opened 2019-07-26 12:19 UTC
## Steps to reproduce

Related issue to [console.create](https://github.com/rapid7/metasploit-framework/issues/11600)

I got my issue after try to create RPC server for Armitage and connect to it.
./armitage -> connection -> exception

## Expected behavior

Connected to RPC, and started Armitage

## Current behavior

Exception
```
Msf::RPC::ServerException (NoMethodError undefined method `migrated' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007f1505520488> ["lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'", "lib/msf/ui/web/console.rb:52:in `initialize'", "lib/msf/ui/web/driver.rb:67:in `new'", "lib/msf/ui/web/driver.rb:67:in `create_console'", "lib/msf/core/rpc/v10/rpc_console.rb:29:in `rpc_create'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])
```
## System stuff

Ruby shell 2.6.2
Ubuntu 18.04.2 LTS

### Metasploit version

MSF 5.0.27 - 38

### I installed Metasploit with:

- Omnibus installer (Tried also Omnibus and still get an error)
- Source install (Tried 2.5.3-2.6.2)

### OS

Ubuntu 18.04.2 LTS

**Comment by mkienow-r7** [comment] 2019-07-29 03:27
@Mrlaminat Thank you for reporting the issue. I'm going to close this issue since the cause is the same as issue #11600.

**Closed by mkienow-r7** 2019-07-29 03:27 UTC
