### ISSUE TITLE
How to create a key in the registry?

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#11425] opened 2019-02-17 11:36 UTC
Hello, i'm trying to create key with RegCreateKeyExA api; registry_createkey isn't satisfied.

 client.railgun.advapi32.RegCreateKeyExA(HKEY_LOCAL_MACHINE,
            "SOFTWARE\\test",
            0,
            "REG_OPTION_VOLATILE",
	    KEY_ALL_ACCESS,
            KEY_SET_VALUE,
            nil,
            nil,
            nil
    )

What am I doing wrong? Please, help me.

**Comment by busterb** [comment] 2019-02-28 20:35
Could we just fix registry_createkey to support what you need? What is it that you want to do, the VOLATILE option?

**Comment by Koraman** [comment] 2019-03-02 01:14
I want to offer you add support of ACL (Access Control List) both for files and registry keys, and for other objects, wmi, for example. It may be helpful.
How do you look at it?

**Comment by ccondon-r7** [comment] 2020-02-14 04:18
Hey there, it's been a while since this conversation was active, and it doesn't seem to be a confirmed bug, so we're closing it out. You can always ask questions about general usage or troubleshooting on Slack: https://metasploit.com/slack

**Closed by ccondon-r7** 2020-02-14 04:18 UTC
Labels: question
