### ISSUE TITLE
migrate is not working in meterpreter?

### ISSUE THREAD

**Issue by agrawalsmart7** [rapid7/metasploit-framework#11008] opened 2018-11-23 08:54 UTC
Hi,

My working environment is:-

Os:- Windows 10
Metasploit version:- v.4.17.25

Problem Description:-

I am facing this error when I migrate to any process. `migrate 1028`

`[-] Error running command migrate: NoMethodError undefined method 'pid' for nil:NilClass`

Can anyone suggest me something?

**Comment by masterka00** [comment] 2018-11-24 12:52
I got the same issue when having a meterpreter shell on a kali linux target.

Metasploit version: 4.17.24-0kali1

**Comment by kirillwow** [comment] 2018-12-03 16:48
See this issue since 4.17.6-dev-

**Comment by bwatters-r7** [comment] 2018-12-04 02:04
Can you give some more information?
You seem to be using meterpreter, but how is it running?  Are you in a stand-alone meterpreter process, or in a DLL.  What processes are you moving in between?  Are they the same architecture?

**Comment by ccondon-r7** [comment] 2020-02-23 22:37
Hi there! We're closing this because it has not been active in more than a year and we do not have enough information to reproduce the issue. If you'd like to give us the information we request in the issue form and re-open it, go ahead. Thanks!

**Closed by ccondon-r7** 2020-02-23 22:37 UTC
Labels: meterpreter
