### ISSUE TITLE
Msf::Ui::Console::CommandDispatcher::Core: datastore validation is too aggressive

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#17886] opened 2023-04-15 10:12 UTC
Metasploit's datastore validation may be too clever for its own good.

There is at least one instance where we want to set `rhost` when it is not an expected value:

```
msf6 post(multi/manage/shell_to_meterpreter) > set payload_override linux/x86/meterpreter/bind_tcp
payload_override => linux/x86/meterpreter/bind_tcp
msf6 post(multi/manage/shell_to_meterpreter) > set rhost 192.168.200.158
[-] Unknown datastore option: rhost. Did you mean LHOST?
msf6 post(multi/manage/shell_to_meterpreter) > set rhost
[-] Unknown datastore option: rhost. Did you mean LHOST?
Usage: set [options] [name] [value]

Set the given option to value.  If value is omitted, print the current value.
If both are omitted, print options that are currently set.

If run from a module context, this will set the value in the module's
datastore.  Use -g to operate on the global datastore.

If setting a PAYLOAD, this command can take an index from `show payloads'.

OPTIONS:

    -g, --global  Operate on global datastore variables

msf6 post(multi/manage/shell_to_meterpreter) > 
```

Bypassed with the following dodgy hack:

```diff
diff --git a/lib/msf/ui/console/command_dispatcher/core.rb b/lib/msf/ui/console/command_dispatcher/core.rb
index d6e9023fb6..33689750f2 100644
--- a/lib/msf/ui/console/command_dispatcher/core.rb
+++ b/lib/msf/ui/console/command_dispatcher/core.rb
@@ -1904,8 +1904,8 @@ class Core
         suggestion = DidYouMean::SpellChecker.new(dictionary: valid_options).correct(args[0]).first
         message << " Did you mean #{suggestion}?" if suggestion
         print_error(message)
-        cmd_set_help
-        return false
+        #cmd_set_help
+        #return false
       end
     end
 
@@ -1937,7 +1937,7 @@ class Core
       suggestion = DidYouMean::SpellChecker.new(dictionary: valid_options).correct(name).first
       message << " Did you mean #{suggestion}?" if suggestion
       print_error(message)
-      return false
+      #return false
     end
 
     # If the driver indicates that the value is not valid, bust out.
```

As the `payload_override` is specified as a string, and is never validated to be a valid `payload`, the associated payload options will never be exposed to the command dispatcher as valid `datastore` options.

**Comment by bcoles** [comment] 2023-04-15 10:13
Issue first identified in #17885.

**Comment by bcoles** [comment] 2023-04-15 10:19
Unfortunately the `set` command does not have an option to force-set a value.

There's `setg` to set an option globally but that's a hacky solution. I would be very careful about setting an `rhost` globally. Also the help command for `setg` is broken (#17887).

**Comment by adfoster-r7** [comment] 2023-04-15 23:50
I believe this is a regression caused by https://github.com/rapid7/metasploit-framework/pull/16774

As suggested - it might be best to just warning the user that their desired datastore option might be wrong, and continue to setting the value, i.e. remove the [return false](https://github.com/rapid7/metasploit-framework/pull/16774/files#diff-8ec504ef60a6490b277e1bbb3ea861d2b33f06f6a380d9a6177ee54c444dc67bR1895)

cc @zeroSteiner Any thoughts?

**Comment by zeroSteiner** [comment] 2023-04-15 23:56
Seems like the module should have an RHOST option registered in the datastore if it's an option that users need to set. I'd be curious if it shows up in the `show options` output and if it does why it's not allowed to be set and if it doesn't then it should probably be registered.

**Comment by bcoles** [comment] 2023-04-16 01:33
> Seems like the module should have an RHOST option registered in the datastore if it's an option that users need to set. I'd be curious if it shows up in the `show options` output and if it does why it's not allowed to be set and if it doesn't then it should probably be registered.

The module does not have an `RHOST` option. It does not show up in `show options` because it is a payload option.

There's a deeper issue here, which I started to type up, but got sidetracked.

Even if this specific issue is resolved, and although this specific issue is rare, this issue indicates that there is at least one instance in the framework where the validation may be too aggressive.

**Comment by adfoster-r7** [comment] 2023-05-03 12:06
I'll close this based on https://github.com/rapid7/metasploit-framework/pull/17911 landing - which is close to the original code snippet suggested by bcoles; if we want to iterate / reopen this though, that works for me too :+1:

**Closed by adfoster-r7** 2023-05-03 12:06 UTC
Labels: bug
