### ISSUE TITLE
Strange charater when pressing key enter

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#8339] opened 2017-05-04 00:03 UTC
## Steps to reproduce

How'd you do it?

1. ... Start msfconsole
2. ... press enter... 
3. ... it get a \r character after key pressed

Im using arch and installed metasploit from the official repo https://wiki.archlinux.org/index.php/Metasploit_Framework (
ruby2.3-2.3.4-2, ruby2.3-bundler-1.14.6-1,  metasploit-4.13.22-1)

How can i hide the \r character? It doesnt affect the metasploit behavior...

Ty

**Comment by wwebb-r7** [comment] 2017-05-04 00:21
Is this in a terminal emulator or the console?  If yes to a terminal emulator, which one?

FWIW I just tried and cannot reproduce it on Arch using rxvt-unicode, Xterm, and terminator with the latest dev branch (which would be metasploit-git on AUR)

**Comment by jchengching** [comment] 2017-05-04 00:39
Hi

its the gnome terminal, i didnt tried in a terminal emulator

**Comment by jchengching** [comment] 2017-05-04 00:52
I will try with installing it from AUR...

**Comment by Spakman** [comment] 2017-05-05 09:47
I'm experiencing the same thing using other rb-readline programs on Arch. The small examples in the rb-readline repositories only experience this behaviour when calling `require "readline.rb"` rather than `require "readline"` but unfortunately my application doesn't do that.

Any idea what package was updated on Arch that may have caused this?

**Comment by jchengching** [comment] 2017-05-05 10:16
Hi

mmm, no ill try to remember, but actually dont have any idea.

Ty

**Comment by wwebb-r7** [comment] 2017-05-05 22:19
Most of us have been doing BSides Austin for the past two days, but we'll look into it on our end when we have a chance.

My setup, where I'm unable to reproduce, is using a manually installed dev environment.  If this actually becomes a problem for anyone, you could always go that route, or if you're really adventurous, you could try one of the deb/rpm nightly installer packages.  (They work great on Debian/RH systems but I personally wouldn't do either on Arch unless I absolutely had to)

**Comment by busterb** [comment] 2017-05-05 22:25
Does 'msfconsole -L' work for you?

**Comment by 3rso** [comment] 2017-05-06 10:29
im getting the same issue, but if i does msfconsole -L the \r character is not shown

**Comment by wizard32** [comment] 2017-05-19 06:00
I can also verify the same behavior. On Arch environment I'm getting also the \r character after pressing the Enter button. Running msfconsole -L as @3rso suggested solves the "problem".

**Comment by SecurityAddicted** [comment] 2017-05-23 12:54
Same here on OSX and Dev install.
`msfconsole -L` fix the issue.

**Comment by Spakman** [comment] 2017-05-27 12:49
I'm tracking this in https://github.com/ConnorAtherton/rb-readline/issues/138 but might as well post it here too.

I've narrowed this down (after breaking `pacman` far too many times...) to something that has changed in a recent ncurses.

* `ncurses-6.0+20170429-1` triggers this problem
* `ncurses-6.0+20170128-1` does not

**Comment by Spakman** [comment] 2017-05-27 15:13
This is fixed in https://github.com/ConnorAtherton/rb-readline/commit/fd882edcd145c26681f9971be5f6675c7f6d1970.

**Comment by busterb** [comment] 2017-07-17 15:24
Pulled in upstream fix with #8732

**Closed by busterb** 2017-07-17 15:24 UTC
