### ISSUE TITLE
-r option in services broken

### ISSUE THREAD

**Issue by rsenet** [rapid7/metasploit-framework#11876] opened 2019-05-23 16:19 UTC
## Steps to reproduce

```
msf5 > services -r tcp
Services
========

host          port   proto  name               state    info
----          ----   -----  ----               -----    ----
10.27.27.103  7      udp    echo               unknown
10.27.27.103  9      udp    discard            unknown
10.27.27.103  13     udp    daytime            unknown
10.27.27.103  17     udp    qotd               unknown
10.27.27.103  37     udp    time               unknown
10.27.27.103  53     udp    domain             unknown
10.27.27.103  67     udp    dhcps              unknown
10.27.27.103  68     udp    dhcpc              unknown
10.27.27.103  69     udp    tftp               unknown
10.27.27.103  80     udp    http               unknown
10.27.27.103  111    udp    rpcbind            unknown
10.27.27.103  121    udp    erpc               unknown
10.27.27.103  123    udp    ntp                unknown
10.27.27.103  135    tcp    msrpc              open
10.27.27.103  135    udp    msrpc              unknown
10.27.27.103  137    udp    netbios-ns         unknown
```

## Expected behavior

Only TCP (-r tcp) or UDP (-r udp) services have to be listed

## Current behavior

All services are currently listed (TCP & UDP)

### Metasploit version

=[ metasploit v5.0.16-dev]

### I installed Metasploit with:
- [**X**] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on? Kali Linux

**Comment by mkienow-r7** [comment] 2019-05-23 18:40
The behavior of the services command was changed by #9717.

Old:
```
-r <protocol>     Only show [tcp|udp] services
```

New:
```
-r <protocol>     Protocol type of the service being added [tcp|udp]
```

You should be able to filter as desired by using the protocol as a search term, for example, `services --search tcp`.

**Comment by wvu-r7** [comment] 2019-05-23 21:05
So it's changed behavior and not a bug? Is that the most specific way you can filter protocol in the `services` command?

```
msf5 > services -a -p 4444 -r udp -s bind_tcp 192.168.1.1
[*] Time: 2019-05-23 21:04:32 UTC Service: host=192.168.1.1 port=4444 proto=udp name=bind_tcp
msf5 > services -S tcp
Services
========

host         port  proto  name      state  info
----         ----  -----  ----      -----  ----
192.168.1.1  4444  udp    bind_tcp  open

msf5 >
```

**Comment by mkienow-r7** [comment] 2019-05-23 21:35
@jbarnett-r7 might recall what he had in mind when making that change. That said, I don't have an issue restoring the previous ability to filter using the various `services` options.

**Comment by jbarnett-r7** [comment] 2019-05-23 21:41
@mkienow-r7 and I definitely had a discussion about this when the change was made. It was intended that the `--search` option was to be used for filtering data. There was actually an older issue where it was brought up that `-p` was no longer filtering by port. It was recommended to revert it, which was done in #9587. 

We can revert this functionality as well if using flags for filtering is preferred, but the `--search` option does offer similar functionality.

**Comment by wvu-r7** [comment] 2019-05-23 22:33
Might be nice to support search operators. As you can see from my example, it's a full text search. I added a UDP protocol with TCP in its name.

**Comment by wvu-r7** [comment] 2019-05-23 22:34
Closing this as it's not a bug.

**Closed by wvu-r7** 2019-05-23 22:34 UTC
