### ISSUE TITLE
msfvenom hangs / takes long with some formats (csharp)

### ISSUE THREAD

**Issue by Juho9179** [rapid7/metasploit-framework#17356] opened 2022-12-10 22:11 UTC
## Steps to reproduce
`msfvenom -p windows/x64/meterpreter_reverse_tcp LHOST=127.0.0.1 LPORT=443 EXITFUNC=thread -f csharp
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x64 from the payload
No encoder specified, outputting raw payload
`

However, when building binaries (such as .exe) with parameters
`msfvenom -p windows/x64/meterpreter_reverse_tcp LHOST=127.0.0.1 LPORT=443 EXITFUNC=thread -f exe -o test.exe`
the process doesn't take long.

## Expected behavior
Payload generation should be significantly faster, as it was in version 6.2.9-dev.

## Current behavior
It takes up to 8 minutes to generate the payload (stageless meterpreter, for instance)

### Metasploit version
Tested on versions:
6.2.26-dev
6.2.29-dev

Bug wasn't present on version
6.2.9-dev

**Comment by adfoster-r7** [comment] 2022-12-10 23:56
Thanks for the bug report; Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/17245

Which should be fixed by https://github.com/rapid7/rex-text/pull/59

**Closed by adfoster-r7** 2022-12-10 23:56 UTC
Labels: bug
