### ISSUE TITLE
SMB fdleak PR removed during refactor, reintroduces bugs

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#5651] opened 2015-07-02 06:56 UTC
The changes in PR #3738 were removed during the SMBServer refactor. This makes it difficult to handle lots of incoming SMB connections without hitting file descriptor limits quickly.

**Comment by jvazquez-r7** [comment] 2015-07-02 15:35
I've reviewed because I cannot remember it being deleted while SMB refactoring. This commit looks suspicious of deleting the #3738 changes https://github.com/rapid7/metasploit-framework/commit/79d393c5aae31145d4f8f606120a739865920afd#diff-a2918abd5bf791e450e6bb86451e3445

ping @wchen-r7 ^^^ since is the author of the last commit, do you mind to verify?

**Comment by wchen-r7** [comment] 2015-07-02 15:54
Yeah I don't know, maybe. The dates are very close.

**Comment by jvazquez-r7** [comment] 2015-07-02 16:56
okey, so confirmed with @wchen-r7 which was just an unintended deletion. So there is any reason to not readd the code on #3739. I think I can add it by myself to the refactored code :) it will be the next ticket I'll work on, prolly next week. @hmoore-r7 if you don't mind once PR is ready I'll assign to you since I bet you're the best qualified to verify I don't wast nothing when readding #3738 :) Thanks all!

**Closed** 2015-07-06 19:25 UTC
Labels: bug
