### ISSUE TITLE
Updating Latest Mimikatz Support

### ISSUE THREAD

**Issue by c0d3xpl0it** [rapid7/metasploit-framework#7494] opened 2016-10-26 09:53 UTC
Hello,

Is there a roadmap for upgrading the Mimikatz to latest version by @gentilkiwi which supports Windows 10 Anniversary update & Windows Server 2016 (1607 - build 14393) ?

**Comment by OJ** [comment] 2016-10-26 15:48
We're actively working on this at the moment (and this issue is a duplicate of a few others, so I'm going to close this one). Thanks.

**Closed by OJ** 2016-10-26 15:48 UTC
