### ISSUE TITLE
Change bundle in Gemfile.Lock

### ISSUE THREAD

**Issue by peterpt** [rapid7/metasploit-framework#19486] opened 2024-09-21 14:47 UTC
Using the current bundle in Gemfile.lock will give a warning on installing dependencies with "bundle install"  and running msfconsole with the following error :

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

If the bundle version in Gemfile.lock is changed to version 2.5.18  then this warning will not show up .

The current bundle version in Gemfile.lock file in github is : 2.1.4

**Comment by adfoster-r7** [comment] 2024-09-21 16:29
Thanks! This warning can be safely ignored

Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/19316

**Closed by adfoster-r7** 2024-09-21 16:29 UTC
Labels: question
