### ISSUE TITLE
Metasploit payload don't connect to my listener.

### ISSUE THREAD

**Issue by Korto9** [rapid7/metasploit-framework#15033] opened 2021-04-11 19:40 UTC
I am running WSL2 kali linux. My payload only work on the same pc that run kali. I think that is because my inet is not a IPV4 adress. I wanted to connect the payload in a pc in the same network. I need help I have been searching for solution for a very long time.

Thank you in advance
![Screenshot_2021-04-11_15_26_37](https://user-images.githubusercontent.com/78448424/114318689-36ee4680-9adc-11eb-8fd0-f946385e3e44.png)
![Screenshot_2021-04-11_15_42_22](https://user-images.githubusercontent.com/78448424/114318799-a106eb80-9adc-11eb-819d-b31ffb03651d.png)

**Comment by Hirpus77** [comment] 2021-04-12 06:16
Good Morning,

I have the very same problem. I tried, after the set up, alsoon different OS (Mac, Windows, BlackArch, Kali) and the problem is always the same. 

Tried also to start the shell from the target computer, but no connection resolved.

The Payload tried were windows/meterpreter/http, windows/meterpreter/https.

Thank you

**Comment by bcoles** [comment] 2021-04-12 06:33
> inet is not a IPV4 adress. 

Yes it is.

> I have the very same problem.

No you don't.

---

It looks like you're struggling with Metasploit fundamentals.

The Metasploit issue tracker is for tracking issues with Metasploit.

Perhaps someone on IRC or Slack can help you out with your question:

* https://www.metasploit.com/help

Closing this issue. If you believe you have encountered a bug, please create a [new issue](https://github.com/rapid7/metasploit-framework/issues/new/choose), ensuring you complete the appropriate issue template.

**Closed by bcoles** 2021-04-12 06:33 UTC
Labels: question

**Comment by Korto9** [comment] 2021-04-12 14:18
What should I do to solve my problem. I know how to use metasploit. Please elebore your answer.
