### ISSUE TITLE
4.14.1 regression in grpc-1.1.2 aborting bunding

### ISSUE THREAD

**Issue by anthraxx** [rapid7/metasploit-framework#8105] opened 2017-03-14 15:49 UTC
## Steps to reproduce

How'd you do it?

bundle-2.3 install -j"$(nproc)" --no-cache --deployment

## Expected behavior

It should succeed to fetch and build all native extensions of the specified dependencies.

## Current behavior

It aborts because of an error (-Werror=shift-negative-value) but we do _not_ specify such (or -Werror in general) ourselves!

```
current directory: /build/metasploit/src/metasploit-framework-4.14.1/vendor/bundle/ruby/2.3.0/gems/grpc-1.1.2/src/ruby/ext/grpc
/opt/ruby2.3/bin/ruby-2.3 -r ./siteconf20170314-515-u0i7fc.rb extconf.rb
Building internal gRPC into /build/metasploit/src/metasploit-framework-4.14.1/vendor/bundle/ruby/2.3.0/gems/grpc-1.1.2/src/ruby/ext/grpc/libs/opt
make: Entering directory '/build/metasploit/src/metasploit-framework-4.14.1/vendor/bundle/ruby/2.3.0/gems/grpc-1.1.2'
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
[C]       Compiling third_party/zlib/gzread.c
[C]       Compiling third_party/zlib/gzwrite.c
[C]       Compiling third_party/zlib/infback.c
[C]       Compiling third_party/zlib/inffast.c
[C]       Compiling third_party/zlib/inflate.c
[C]       Compiling third_party/zlib/inftrees.c
[C]       Compiling third_party/zlib/trees.c
[C]       Compiling third_party/zlib/uncompr.c
[C]       Compiling third_party/zlib/zutil.c
[C]       Compiling third_party/boringssl/crypto/aes/aes.c
[C]       Compiling src/boringssl/err_data.c
[C]       Compiling third_party/boringssl/crypto/aes/mode_wrappers.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bitstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_bool.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_d2i_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_dup.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_gentm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_i2d_fp.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_mbstr.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_object.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_octet.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_print.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_strnid.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_time.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_type.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utctm.c
[C]       Compiling third_party/boringssl/crypto/asn1/a_utf8.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_lib.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn1_par.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_int.c
[C]       Compiling third_party/boringssl/crypto/asn1/asn_pack.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_string.c
[C]       Compiling third_party/boringssl/crypto/asn1/f_enum.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_dec.c
[C]       Compiling third_party/boringssl/crypto/asn1/t_bitst.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_enc.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_fre.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_new.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_typ.c
[C]       Compiling third_party/boringssl/crypto/asn1/x_bignum.c
[C]       Compiling third_party/boringssl/crypto/asn1/tasn_utl.c
[C]       Compiling third_party/boringssl/crypto/asn1/x_long.c
[C]       Compiling third_party/boringssl/crypto/base64/base64.c
[C]       Compiling third_party/boringssl/crypto/bio/bio.c
[C]       Compiling third_party/boringssl/crypto/bio/buffer.c
[C]       Compiling third_party/boringssl/crypto/bio/bio_mem.c
[C]       Compiling third_party/boringssl/crypto/bio/file.c
[C]       Compiling third_party/boringssl/crypto/bio/fd.c
[C]       Compiling third_party/boringssl/crypto/bio/connect.c
[C]       Compiling third_party/boringssl/crypto/bio/hexdump.c
third_party/zlib/inflate.c: In function ‘inflateMark’:
third_party/zlib/inflate.c:1507:61: error: left shift of negative value [-Werror=shift-negative-value]
     if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                             ^~
[C]       Compiling third_party/boringssl/crypto/bio/pair.c
[C]       Compiling third_party/boringssl/crypto/bio/printf.c
[C]       Compiling third_party/boringssl/crypto/bio/socket.c
[C]       Compiling third_party/boringssl/crypto/bio/socket_helper.c
[C]       Compiling third_party/boringssl/crypto/bn/add.c
[C]       Compiling third_party/boringssl/crypto/bn/asm/x86_64-gcc.c
[C]       Compiling third_party/boringssl/crypto/bn/bn.c
[C]       Compiling third_party/boringssl/crypto/bn/bn_asn1.c
[C]       Compiling third_party/boringssl/crypto/bn/cmp.c
[C]       Compiling third_party/boringssl/crypto/bn/convert.c
[C]       Compiling third_party/boringssl/crypto/bn/ctx.c
[C]       Compiling third_party/boringssl/crypto/bn/div.c
[C]       Compiling third_party/boringssl/crypto/bn/exponentiation.c
[C]       Compiling third_party/boringssl/crypto/bn/gcd.c
[C]       Compiling third_party/boringssl/crypto/bn/generic.c
[C]       Compiling third_party/boringssl/crypto/bn/kronecker.c
[C]       Compiling third_party/boringssl/crypto/bn/montgomery.c
[C]       Compiling third_party/boringssl/crypto/bn/montgomery_inv.c
[C]       Compiling third_party/boringssl/crypto/bn/mul.c
[C]       Compiling third_party/boringssl/crypto/bn/prime.c
[C]       Compiling third_party/boringssl/crypto/bn/random.c
[C]       Compiling third_party/boringssl/crypto/bn/rsaz_exp.c
[C]       Compiling third_party/boringssl/crypto/bn/shift.c
[C]       Compiling third_party/boringssl/crypto/bn/sqrt.c
[C]       Compiling third_party/boringssl/crypto/buf/buf.c
[C]       Compiling third_party/boringssl/crypto/bytestring/asn1_compat.c
[C]       Compiling third_party/boringssl/crypto/bytestring/ber.c
[C]       Compiling third_party/boringssl/crypto/bytestring/cbb.c
[C]       Compiling third_party/boringssl/crypto/bytestring/cbs.c
[C]       Compiling third_party/boringssl/crypto/chacha/chacha.c
[C]       Compiling third_party/boringssl/crypto/cipher/aead.c
[C]       Compiling third_party/boringssl/crypto/cipher/cipher.c
[C]       Compiling third_party/boringssl/crypto/cipher/derive_key.c
[C]       Compiling third_party/boringssl/crypto/cipher/e_aes.c
[C]       Compiling third_party/boringssl/crypto/cipher/e_chacha20poly1305.c
cc1: all warnings being treated as errors
make: *** [Makefile:2291: /build/metasploit/src/metasploit-framework-4.14.1/vendor/bundle/ruby/2.3.0/gems/grpc-1.1.2/src/ruby/ext/grpc/objs/opt/third_party/zlib/inflate.o] Error 1
```

### Metasploit version

4.14.1 release tarball

### I installed Metasploit with:
- [x] Source install (ruby 2.3)

### OS

Arch Linux

cheers,
anthraxx

**Comment by busterb** [comment] 2017-03-14 16:58
what target OS / architecture are you building on?

**Comment by anthraxx** [comment] 2017-03-14 17:22
it was the i686 variant (32bit) of the metasploit package (i need this for packaging, i  don't use 32bit :stuck_out_tongue_closed_eyes: )

**Comment by busterb** [comment] 2017-03-14 20:17
got it, would you mind verifying if #8101 resolves the issue for you?

**Comment by busterb** [comment] 2017-03-14 21:02
Should be fixed now that we've added a whitelist for platforms that don't match the prebuild gem binaries. This is a new feature that shouldn't break anything else if it's omitted for now.

**Comment by anthraxx** [comment] 2017-03-14 21:09
hm I'm not quite sure i understood the whole context of the fix, does that mean I'm pulling pre-compiled binaries now? Because I actually want to build everything from source rather then take some binary artifacts :stuck_out_tongue_closed_eyes:

**Comment by busterb** [comment] 2017-03-14 21:13
The problem is that the currently-released version of the grpc gem builds with -Werror hardcoded in cflags, which causes the whole build to fail if your compiler generates a warning. But, the 'metasploit-aggregator' gem is somewhat optional anyway, and grpc should be fixed in their upcoming release on the 20th. For now, this is the best we can do, shy of suggesting you use a different compiler for the next 6 days.

**Comment by anthraxx** [comment] 2017-03-14 21:34
I see, well doesn't look like clang likes it either :smile_cat: I try to append that to the release tarball Gemfile.lock thingie until the next release

**Comment by busterb** [comment] 2017-03-29 20:38
This should be resolved now - poke me if it's not.

**Closed by busterb** 2017-03-29 20:38 UTC

**Comment by anthraxx** [comment] 2017-04-03 13:32
@busterb 
When I try to bundle it i get 
```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

the dependencies in your gemfile changed


You have deleted from the Gemfile:
* metasploit-aggregator
```

Is it safe to just purge ```metasploit-aggregator``` from the Gemfile.lock, or what is the best option in your opinion?

**Comment by busterb** [comment] 2017-04-03 13:42
If you modify Gemfile, or gemspec, you need to update Gemfile.lock yourself.

Here's how we handled it in the omnibus packager:
https://github.com/rapid7/metasploit-omnibus/commit/e61b52c512ed082f108b8554d28c8abefcf089b0

We do bundle install, which writes a new Gemfile.lock, then we include the updated file in our package.

**Comment by anthraxx** [comment] 2017-04-03 13:46
sure, but i didn't modify it, i just take it as is in the release tarball. I assume maybe because of the conditional stuff in the Gemfile?

**Comment by busterb** [comment] 2017-04-03 13:53
Exactly, it's the conditional stuff in the Gemfile that is causing the modification.

Just package the modified Gemfile.lock that gets generated and it should work fine.
