### ISSUE TITLE
nokogiri error

### ISSUE THREAD

**Issue by mathanmithun** [rapid7/metasploit-framework#12350] opened 2019-09-23 18:05 UTC
Could not find nokogiri-1.10.4 in any of the sources
Run `bundle install` to install missing gems.

**Comment by bwatters-r7** [comment] 2019-09-23 19:41
Did you run `bundle install`?

**Comment by MoacirPetry** [comment] 2019-09-25 18:19
Try delete the file "Gemfile.lock" and after that try the command: `bundle install`

**Comment by h00die** [comment] 2019-09-26 01:29
also, try giving more details on what operating system you are running.  If this is termux, you'll have to ask them for help.

**Comment by jmartin-r7** [comment] 2019-10-04 15:06
No additional details offered, closing as user env related, not a bug in framework project.

**Closed by jmartin-r7** 2019-10-04 15:06 UTC
Labels: library
