### ISSUE TITLE
Error when generating osx reverse https payload with UUID

### ISSUE THREAD

**Issue by phra** [rapid7/metasploit-framework#12869] opened 2020-01-21 13:40 UTC
## Steps to reproduce

1. `use payload/osx/x64/meterpreter_reverse_https`
2. `set lhost eth0`
3. `set lport 443`
4. `set PayloadUUIDName test`
5. `set PayloadUUIDTracking true`
6. `generate -f macho -o rev-https-test.macho`

## Expected behavior

The payload is generated and added to `~/.msf4/payloads.json`

## Current behavior

What happens instead?

```
msf5 payload(osx/x64/meterpreter_reverse_https) > set PayloadUUIDTracking true
PayloadUUIDTracking => true
msf5 payload(osx/x64/meterpreter_reverse_https) > generate -f macho -o rev-https-test.macho

[*] Meterpreter will verify SSL Certificate with SHA1 hash XXXX
[-] Payload generation failed: undefined method `get_payload' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00000000086652a8>
Did you mean?  get_data
```

### Metasploit version

```
Framework: 5.0.68-dev
Console  : 5.0.68-dev
```

### I installed Metasploit with:
- [x] Kali package via apt

**Comment by phra** [comment] 2020-01-21 14:15
maybe related to https://github.com/rapid7/metasploit-framework/pull/11887

**Comment by timwr** [comment] 2020-04-15 09:16
Closing this because I can't reproduce it.

**Closed by timwr** 2020-04-15 09:16 UTC
Labels: bug
