### ISSUE TITLE
Docker Container Missing PostgreSQL

### ISSUE THREAD

**Issue by tekwizz123** [rapid7/metasploit-framework#17231] opened 2022-11-05 23:18 UTC
## Steps to reproduce

```
PS C:\Users\tekwizz123-research>docker pull metasploitframework/metasploit-framework
```
Then opened up the image in Docker Desktop and clicked on the Run button

Btw doing this will fail

```
docker run --name metasploit -it metasploitframework/metasploit-framework:latest
```

Then inside the container:

```
/usr/src/metasploit-framework $ ./msfdb start
[!] You need to have postgres installed or specify a database with --connection-string
/usr/src/metasploit-framework $ ./msfdb status
[!] You need to have postgres installed or specify a database with --connection-string
/usr/src/metasploit-framework $ uname -a
Linux 3795f98a26bd 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
/usr/src/metasploit-framework $
```

## Were you following a specific guide/tutorial or reading documentation?

Found whilst talking with @sneakerhax r.e why they were building custom Docker images for Metasploit.

## Expected behavior

We should have the default set up with a working database connection to allow users to use our database features in their Docker container.

## Current behavior

No database connection is available.

### Metasploit version

Welll.... the image wasn't updated in a year or so, so its version 6.0.55-dev at the moment.

**Comment by tekwizz123** [comment] 2022-11-05 23:24
Oh and also to prove that it isn't installed, here is me installing the `postgresql` package using `apk`:

```
/usr/src/metasploit-framework # apk add postgresql
(1/7) Installing libedit (20191231.3.1-r0)
(2/7) Installing postgresql-client (12.10-r0)
(3/7) Installing tzdata (2022a-r0)
(4/7) Installing libxml2 (2.9.14-r0)
(5/7) Installing llvm10-libs (10.0.0-r2)
(6/7) Installing icu-libs (67.1-r0)
(7/7) Installing postgresql (12.10-r0)
Executing postgresql-12.10-r0.pre-install
Executing busybox-1.31.1-r20.trigger
OK: 496 MiB in 99 packages
/usr/src/metasploit-framework # apk add postgresql
OK: 496 MiB in 99 packages
/usr/src/metasploit-framework #
```

**Comment by gwillcox-r7** [comment] 2022-11-15 17:21
Further investigation shows that this is actually meant to be set up using Docker compose. Closing this down as the current behavior is working as intended.

**Closed by gwillcox-r7** 2022-11-15 17:21 UTC
Labels: bug

**Comment by lmaddox** [comment] 2024-07-14 04:44
An example of how to set it up using Docker compose (for posterity):
https://gist.github.com/ambalabanov/cd8798daeb8b840b99387ce613bf743c
