### ISSUE TITLE
portfwd in meterpreter kills session when used with autoroute 0.0.0.0/0

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#5795] opened 2015-07-31 22:37 UTC
![image](https://cloud.githubusercontent.com/assets/1756255/9018969/ef593f60-3799-11e5-8561-bc6cac4e8a5e.png)

this is bad :\
It's only started happening after I did ./msfupdate this morning

**Comment by bcook-r7** [comment] 2015-07-31 22:44
Hmm, it has been a couple of weeks since we have put out any new meterpreter changes.

Can you say which meterpreter this is and how long ago it was since you ran 'msfupdate' ? Perhaps what OS you're running on as well?

**Comment by Viss** [comment] 2015-07-31 22:45
Sure - this is metasploit v4.11.3-dev-629afd86 
And I ran msfupdate about 2 hours ago.
Running on Ubuntu

**Comment by bcook-r7** [comment] 2015-07-31 22:54
What is the meterpreter payload you are using?

```
payload => windows/meterpreter/reverse_tcp
lhost => 192.168.56.1
...
[*] Sending stage (885806 bytes) to 192.168.56.102
[*] Meterpreter session 1 opened (192.168.56.1:4444 -> 192.168.56.102:57214) at 2015-07-31 17:53:06 -0500
meterpreter > portfwd add -l 3389 -p 3389 -r localhost
[*] Local TCP relay created: 0.0.0.0:3389 <-> localhost:3389
```

**Comment by Viss** [comment] 2015-07-31 22:59
windows/meterpreter_reverse_tcp

**Comment by Viss** [comment] 2015-07-31 23:00
msf post(download_exec) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > portfwd add -l 3389 -p 3389 -r localhost

[*] 172.18.200.140 - Meterpreter session 1 closed.

**Comment by bcook-r7** [comment] 2015-07-31 23:04
I have not been able to reproduce this yet. Can I suggest simply rolling back to the earlier version you had checked out - it looks like you are using the git version of framework. Something like:

git checkout @{two.days.ago}

that reflects when you updated last and things worked properly? This is to verify that earlier versions still work, and there is not some other sort of issue tangential to framework being updated.

**Comment by Viss** [comment] 2015-07-31 23:08
hrm. I can try. I'm on a live gig and I have ~20 live shells, so I'll have to sort out a way to stash them somewhere to test this

**Comment by bcook-r7** [comment] 2015-07-31 23:13
I see. Were these shells live before you updated framework, and how old was framework before you updated?

**Comment by Viss** [comment] 2015-07-31 23:14
![image](https://cloud.githubusercontent.com/assets/1756255/9019366/32e30d42-379f-11e5-90a4-bf79db16e015.png)

Oh interesting! so I did what you asked with git, re opened msf (all my shells came back! :D)
and now it 'works'

**Comment by Viss** [comment] 2015-07-31 23:15
I update framework probably once every day or two. I usually do it right before a gig, and if it ever crashes on me (it did yesterday.. i typed use use <modulename> and it appeared to barf HARD), i update it.

**Comment by bcook-r7** [comment] 2015-07-31 23:18
Glad to hear you got over the hump at least. I guess that pinpoints the problem within the last 2 days of commits. Not to distract you from your gig, but if you get to a stopping point and can reproduce again after running './msfupdate', we can use 'git bisect' to pinpoint the issue. Not a huge amount has gone in in the last 2 days - your failing version was from right when 629afd86 went in the tree.

**Comment by Viss** [comment] 2015-07-31 23:21
well i have msf pro up and running with a shitton of shells, so I can burn these for now and reget them later - what would you like me to do?

**Comment by Viss** [comment] 2015-07-31 23:22
(the thing that pro lets me do which is neat is say - here, run psexec against this /24, where framework its this huge painful process of copypasting to a text editor then making 100 lines of console commands and then pasting them back in)

**Comment by Viss** [comment] 2015-07-31 23:41
so msfupdate only touched a few files:
![image](https://cloud.githubusercontent.com/assets/1756255/9019564/b672b286-37a2-11e5-9269-69f05fd91db9.png)


.... and uh... now it... just works
![image](https://cloud.githubusercontent.com/assets/1756255/9019572/e858dc44-37a2-11e5-9a58-728c5db761a5.png)

loldogscience.jpg. I have no idea.

**Comment by Viss** [comment] 2015-08-01 00:11
WAIT, it's doing it again
![image](https://cloud.githubusercontent.com/assets/1756255/9019809/3acccdce-37a7-11e5-9774-61bb176806e2.png)

**Comment by Viss** [comment] 2015-08-01 00:12
I think it has something to do with autoroute - because it didn't start barfing again until I did 
autoroute -s 0.0.0.0/0 
on one of the other sessions

**Comment by Viss** [comment] 2015-08-01 00:13
Yup. session 1 was the one with the autoroute, I try it again on session 2 and it works
![image](https://cloud.githubusercontent.com/assets/1756255/9019818/6ff2ae74-37a7-11e5-897f-c47bd49bcd44.png)

**Comment by Viss** [comment] 2015-08-01 00:13
so there's some kind of conflict between portfwd and autoroute

**Comment by bcook-r7** [comment] 2015-08-01 21:46
Thanks! that gives us something more to chew on.

**Comment by Viss** [comment] 2015-08-15 22:01
some more updated info:

If specific routes are defined.. (run autoroute -s 10.0.0.0/24, etc) it seems to behave.
The only time the problem triggers is if 0.0.0.0/0 is used as the route.

**Comment by wvu-r7** [comment] 2015-08-17 15:39
@Viss: Are you trying to set a default route with ```autoroute```?

**Comment by Viss** [comment] 2015-08-17 16:30
@wvu-r7 yeah, and it totally works! Just.. not at the same time as portfwd.

**Comment by ccondon-r7** [comment] 2020-02-28 15:47
Closing this because it's been (gulp) 4.5 years since it was active. If still an issue on latest MSF, feel free to reopen and ping!

**Closed by ccondon-r7** 2020-02-28 15:47 UTC
Labels: library, meterpreter
