### ISSUE TITLE
Stuck at Decompiling original apk

### ISSUE THREAD

**Issue by prashasst** [rapid7/metasploit-framework#13379] opened 2020-05-02 17:13 UTC
It is stuck at decompiling original apk
![Screenshot_20200502-224022_Termux](https://user-images.githubusercontent.com/55028965/80870791-62f72a00-8cc6-11ea-83ed-e01095421635.jpg)

**Comment by gwillcox-r7** [comment] 2020-05-24 17:55
@prashasst If you are able to reproduce this issue on a non-Termux machine, I will be happy to look into this further. Otherwise for the moment, since this may be a Termux specific issue, I am going to close this issue out until further evidence can be presented. Feel free to reply if you have evidence of this same issue occurring on a non-Termux machine, such as Windows, Mac, or Linux machine with the latest Metasploit version installed. Also please be aware that Metasploit does not officially support version 2.7.x of Ruby right now, so this is something to keep in mind.

Thanks,
Grant

**Closed by gwillcox-r7** 2020-05-24 17:55 UTC
Labels: termux

**Comment by kviraj572** [comment] 2023-12-24 06:36
> @prashasst If you are able to reproduce this issue on a non-Termux machine, I will be happy to look into this further. Otherwise for the moment, since this may be a Termux specific issue, I am going to close this issue out until further evidence can be presented. Feel free to reply if you have evidence of this same issue occurring on a non-Termux machine, such as Windows, Mac, or Linux machine with the latest Metasploit version installed. Also please be aware that Metasploit does not officially support version 2.7.x of Ruby right now, so this is something to keep in mind.


> 
> Thanks, Grant

i have the same issue on parrot os can u please help

![Screenshot at 2023-12-24 06-35-27](https://github.com/rapid7/metasploit-framework/assets/128163957/3343d155-6a58-413f-a61b-bcf8fae265dd)
