### ISSUE TITLE
You have bug in enable_rdp.

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-framework#13621] opened 2020-06-13 20:21 UTC
In string 155. (HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList) we set path, and use  registry_setvaldata(hide_user_key, username, 0, "REG_DWORD"), for create. 
But if computer isn't have key UserList, or SpecialAccounts, we can't create key.

We must use create_key(hide_user_key), before setvaldata.
Please, fix it.

**Comment by bcoles** [comment] 2020-06-13 20:44
Dupe of #11221

**Closed by bcoles** 2020-06-13 20:44 UTC
