### ISSUE TITLE
Armitage error

### ISSUE THREAD

**Issue by raabbit101** [rapid7/metasploit-framework#18939] opened 2024-03-08 21:20 UTC
Hi. can somone help with error in armitage please?? 

msf6 auxiliary(scanner/portscan/tcp) > run -j
[-] Auxiliary failed: NoMethodError undefined method `prompting' for #<Msf::Ui::Web::WebConsole::WebConsolePipe:0x00007f9258679840 @subscribers_out={"msfweb"=>#<Rex::Ui::Text::Output::Buffer:0x00007f9258681ab8 @buf="">}, @subscribers_ref={}, @subscribers_idx=0, @pipe_input=#<Rex::Ui::Text::Input::Buffer:0x00007f9258679778 @sock=#<Rex::Ui::Text::Input::Buffer::BufferSock:0x00007f9258679728 @lsock=#<TCPSocket:fd 19, AF_INET, 127.0.0.1, 40005>, @rsock=#<TCPSocket:fd 18, AF_INET, 127.0.0.1, 38922>>>, @output=#<Msf::Ui::Web::WebConsole::WebConsolePipe:0x00007f9258679840 ...>, @input=nil, @prompt="msf6 auxiliary(scanner/portscan/tcp) > ">
Did you mean?  prompting?
               prompt
               prompt=
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:280:in `ensure in without_prompt'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:280:in `without_prompt'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:245:in `alert_user'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/ui.rb:21:in `init_ui'

**Comment by nrathaus** [comment] 2024-04-05 15:29
Duplicate of https://github.com/rapid7/metasploit-framework/issues/18966

Verify you are running latest version of metasploit

**Comment by adfoster-r7** [comment] 2024-04-05 15:42
Confirmed as working on the latest version of Metasploit - 6.4.0+

Closing :+1:

**Closed by adfoster-r7** 2024-04-05 15:42 UTC
Labels: bug
