### ISSUE TITLE
prosvc.rb Failing

### ISSUE THREAD

**Issue by themazzaroth** [rapid7/metasploit-framework#5562] opened 2015-06-18 18:54 UTC
So I have been reading all about the different problems people have been having since upgrading their msfconsole, but this has been happening for awhile now. As far back as 1.08. If you try and run /opt/metasploit/apps/pro/engine/prosvc.rb it gives you an error that it can't find rake-10.4.2 in any of the sources. (bundler::GemNotFound)  I try and gem install rake and that doesn't fix it either.
 I am trying to get the rpc server working, and I think this is the root cause.

I am also still having the issue when I try and run msfconsole it dies, and I tried upgrading at 13:47 on 6/18/2015.

**Comment by kernelsmith** [comment] 2015-06-18 22:19
Try this, from Metasploit's installlation/git directory

```Shell
gem install rake
gem install bundler (if the command below fails)
bundle install
```

**Comment by bcook-r7** [comment] 2015-06-22 16:34
I believe this is an issue with the metasploit pro product or kali linux, not metasploit framework. I created internal issue MSP-12839 to track this.

**Comment by bcook-r7** [comment] 2015-06-22 17:37
We will need more information to triage this, such as the platform you are using (Kali?). Also, the msfconsole issue should be fixed when Kali linux is updated next (ETA mid-week).

**Comment by themazzaroth** [comment] 2015-06-22 17:46
Thanks for getting back to me. I am running Kali 1.1. I did a clean install, like no kidding downloaded a brand new image from the Kali website apt-get update && apt-get upgrade and then tried to start  prosvc.rb. 
![kali_prosvc](https://cloud.githubusercontent.com/assets/2363694/8288570/a4963662-18dc-11e5-919b-e7d3faf5319c.png)

**Comment by bcook-r7** [comment] 2015-06-22 18:01
Ah - the problem you are hitting is expected and is based on the way you are invoking ruby. Metasploit, since moving to ruby 2.1, has bundled its own ruby installation when installed on Kali linux since Kali only supports 1.9. You appear to be trying to run prosvc.rb with Kali Linux's system ruby, which is not a usable version. I would suggest starting prosvc from the RC scripts instead. 

If you really want to run it from the command line like this, you would need to at least have the correct version of ruby in the path. This may work (haven't tested):

```
export PATH=/opt/metasploit/ruby/bin:$PATH
ruby prosvc.rb
```

**Comment by themazzaroth** [comment] 2015-06-22 18:20
Ok,  ran ruby from the metasploit directory, but still getting errors. These errors appear to be in the flavor of what other people have been reporting. I am going stop debugging until that update is pushed, then I will report back/close if it resolves the issue.

**Comment by todb-r7** [comment] 2015-06-23 06:07
Looks like this morphed into a dupe of #5553, then. Closing.

**Closed by todb-r7** 2015-06-23 06:07 UTC
