### ISSUE TITLE
The payload-APK I created is not loading

### ISSUE THREAD

**Issue by ffff8** [rapid7/metasploit-framework#13743] opened 2020-06-20 10:20 UTC
The application that worked seamlessly with **Android 9**, 1 week ago is not currently running in the same version. I think this problem is caused by Metasploit.

**Comment by smcintyre-r7** [comment] 2020-06-22 13:08
If you think the issue is caused by Metasploit, then it would be helpful if you could:

1. Send us both versions of Metasploit, the one that worked and the one that did not work.
1. Confirm that the one that originally worked, is still working in your environment with the same setup.

**Comment by ffff8** [comment] 2020-06-22 13:39
> If you think the issue is caused by Metasploit, then it would be helpful if you could:
> 
> 1. Send us both versions of Metasploit, the one that worked and the one that did not work.
> 2. Confirm that the one that originally worked, is still working in your environment with the same setup.

Hello I get such an error when I completely uninstall and reinstall it
#13749

**Comment by gwillcox-r7** [comment] 2020-06-22 21:38
Please follow the issue template when creating issues. As you have not followed the template and seem to have created a separate issue at #13749 to track this issue. I am going to close this issue.

**Closed** 2020-06-22 21:39 UTC
Labels: bug, potato
