### ISSUE TITLE
Several Errors After Updating

### ISSUE THREAD

**Issue by init5-SF** [rapid7/metasploit-framework#16853] opened 2022-08-02 17:57 UTC
## Steps to reproduce

I just did apt update and apt upgrade, metasploit was one of the upgradable packages.

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Running msfconsole or msfvenom should behave normally

## Current behavior

I get these errors when I use msfconsole or msfvenom

```
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
```

### Metasploit version

Framework: 6.2.9-dev
Console  : 6.2.9-dev

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: postgresql selected, no connection
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
2000   version
2001   debug
2002   set loglevel 3
2003   clear
2004   debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[08/02/2022 19:45:31] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:31] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:34] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:45] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[04/02/2022 16:06:10] [w(0)] core: 	/usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go
[04/02/2022 16:06:10] [w(0)] core: 	/usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go
[04/02/2022 16:06:10] [d(0)] core: HistoryManager.push_context name: :msfconsole
[04/02/2022 16:06:30] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[04/12/2022 17:46:48] [e(0)] core: Failed to connect to the database: No database YAML file
[04/12/2022 17:46:48] [d(0)] core: Updated user based module store
[04/12/2022 17:46:51] [d(0)] core: HistoryManager.push_context name: :msfconsole
[04/12/2022 17:46:51] [e(0)] core: Failed to connect to the database: No database YAML file
[04/12/2022 17:47:15] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[04/12/2022 17:48:46] [e(0)] core: Failed to connect to the database: No database YAML file
[04/12/2022 17:48:48] [d(0)] core: HistoryManager.push_context name: :msfconsole
[04/12/2022 17:48:52] [e(0)] core: Failed to connect to the database: No database YAML file
[04/12/2022 17:48:59] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[04/15/2022 17:52:13] [e(0)] core: Failed to connect to the database: No database YAML file
[04/15/2022 17:52:20] [e(0)] core: Failed to connect to the database: No database YAML file
[04/15/2022 17:52:22] [d(0)] core: HistoryManager.push_context name: :msfconsole
[04/15/2022 17:52:36] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[04/20/2022 12:55:00] [e(0)] core: Failed to connect to the database: No database YAML file
[04/21/2022 17:02:24] [d(0)] core: Updated user based module store
[04/21/2022 17:02:25] [e(0)] core: Failed to connect to the database: No database YAML file
[04/21/2022 17:02:33] [e(0)] core: Failed to connect to the database: No database YAML file
[04/21/2022 17:02:35] [d(0)] core: HistoryManager.push_context name: :msfconsole
[04/21/2022 17:02:38] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[04/23/2022 15:47:49] [e(0)] core: Failed to connect to the database: No database YAML file
[05/16/2022 19:02:54] [d(0)] core: Updated user based module store
[05/16/2022 19:02:56] [e(0)] core: Failed to connect to the database: No database YAML file
[05/16/2022 19:03:00] [e(0)] core: Failed to connect to the database: No database YAML file
[05/16/2022 19:03:04] [d(0)] core: HistoryManager.push_context name: :msfconsole
[05/16/2022 19:03:08] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[05/30/2022 19:47:16] [e(0)] core: Failed to connect to the database: No database YAML file
[05/30/2022 19:58:09] [e(0)] core: Failed to connect to the database: No database YAML file
[05/30/2022 19:58:26] [e(0)] core: Failed to connect to the database: No database YAML file
[05/30/2022 20:00:02] [e(0)] core: Failed to connect to the database: No database YAML file
[05/30/2022 20:00:04] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:45:29] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:45:29] [d(0)] core: Updated user based module store
[08/02/2022 19:45:31] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:31] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:31] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:32] [d(0)] core: HistoryManager.push_context name: :msfconsole
[08/02/2022 19:45:34] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:45:35] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:46:15] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[08/02/2022 19:52:45] [e(0)] core: Failed to connect to the database: No database YAML file
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:47] [e(0)] core: OpenSSL::PKey::PKeyError pkeys are immutable on OpenSSL 3.0
[08/02/2022 19:52:49] [d(0)] core: HistoryManager.push_context name: :msfconsole
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.2.9-dev
Ruby: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]
OpenSSL: OpenSSL 3.0.3 3 May 2022
Install Root: /usr/share/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Other - Please specify
```

</details>

**Comment by gwillcox-r7** [comment] 2022-08-02 22:35
Those are warnings not errors. They should not prevent normal operation of Metasploit.

**Comment by adfoster-r7** [comment] 2022-08-02 23:18
Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/16818

These are warnings related to OpenSSL 3 and can be ignored 👍

**Closed by adfoster-r7** 2022-08-02 23:18 UTC
Labels: bug

**Comment by init5-SF** [comment] 2022-08-03 00:11
@adfoster-r7 Thanks for the info, is there a way to fix it and prevent those warnings?
