### ISSUE TITLE
I have a question when I start the msfconsole.

### ISSUE THREAD

**Issue by OldDream666** [rapid7/metasploit-framework#16896] opened 2022-08-11 16:37 UTC
## Relevant information

like this
![截图_2022-08-12_00-36-07](https://user-images.githubusercontent.com/89271654/184185198-2b21a096-16e2-4165-baf8-bba19dc643b5.png)
I don't know it how to fix. But it always warning me every times.
hope u can help me thanks

**Comment by adfoster-r7** [comment] 2022-08-11 16:48
Thanks for raising an issue; That warning can safely be ignored for now :+1:

**Comment by adfoster-r7** [comment] 2022-08-11 16:49
Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/16818 - which will fix this ignorable warning in an upcoming release

**Closed by adfoster-r7** 2022-08-11 16:48 UTC
Labels: question

**Comment by OldDream666** [comment] 2022-08-11 16:50
> 

ok thanks
