### ISSUE TITLE
APKTool 2.2.2 fails to rebuild APK after injection

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#8829] opened 2017-08-13 19:06 UTC
While attempting to use msfvenom to impregnate an APK, i ran into the following messages for a number of APKs including ones i've used before:
```
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Rebuilding com.rascarlo.aurdroid_2.apk with meterpreter injection as /tmp/d20170813-28706-k8hfwn/output.apk
Error: Unable to rebuild apk with apktool
$ apktool -v
Apktool v2.2.2 - a tool for reengineering Android apk files
with smali v2.1.3 and baksmali v2.1.3
```
This is on Arch Linux using blackarch repos at current revisions.
Relevant package versions:
```
android-apktool 2.2.2-1
android-ndk 1:r14b-1
android-sdk 26.0.2-1
android-sdk-build-tools r26.0.1-1
android-sdk-platform-tools r26.0.0-1
```
I've tried this with the Framework version provided by BlackArch (upstream AFAIK) as well as mine. Probably to do with a recent SDK version upgrade.
There's not much to go on in the error message
Ping @timwr @OJ @bcook-r7  - if this is indeed a versioning issue, Arch is a good barometer for things to come in other distros.

**Comment by sempervictus** [comment] 2017-08-13 19:07
Known working APK can be found @ _https://f-droid.org/repo/com.rascarlo.aurdroid_2.apk_ which i've successfully backdoor-ed before.

**Comment by sempervictus** [comment] 2017-08-13 20:12
Found it - apparently Google thinks its a brilliant idea to have /tmp be executable.
We should document somewhere that this process will fail if /tmp is mounted noexec.
Remounting -o remount,exec fixed the "problem"

**Comment by sempervictus** [comment] 2017-08-13 21:02
Reopening as the resulting APK does not connect back with meterp or shell payloads. Something's amiss here.

**Comment by timwr** [comment] 2017-09-11 03:49
@sempervictus I can't reproduce this. The above APK gives me a working session
```
meterpreter > pwd
/data/data/com.rascarlo.aurdroid/files
```

**Comment by timwr** [comment] 2017-10-31 03:01
Closing this. Feel free to re-open if you can reproduce it.

**Closed by timwr** 2017-10-31 03:01 UTC
Labels: bug
