### ISSUE TITLE
Armitage: Auxiliary failed: NoMethodError undefined method `prompting'

### ISSUE THREAD

**Issue by alyaparan** [rapid7/metasploit-framework#18966] opened 2024-03-15 12:03 UTC
msf6 auxiliary(scanner/portscan/tcp) > set PORTS 5671, 50000, 21, 1720, 80, 443, 143, 623, 3306, 110, 5432, 25, 22, , 23, 1521, 50013, 161, 2222, 17185, 135, 8080, 4848, 1433, 5560, 512, 513, 514, 445, 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909, 5038, 111, 139, 49, 515, 7787, 2947, 7144, 9080, 8812, 2525, 2207, 3050, 5405, 1723, 1099, 5555, 921, 10001, 123, 3690, 548, 617, 6112, 6667, 3632, 783, 10050, 38292, 12174, 2967, 5168, 3628, 7777, 6101, 10000, 6504, 41523, 41524, 2000, 1900, 10202, 6503, 6070, 6502, 6050, 2103, 41025, 44334, 2100, 5554, 12203, 26000, 4000, 1000, 8014, 5250, 34443, 8028, 8008, 7510, 9495, 1581, 8000, 18881, 57772, 9090, 9999, 81, 3000, 8300, 8800, 8090, 389, 10203, 5093, 1533, 13500, 705, 4659, 20031, 16102, 6080, 6660, 11000, 19810, 3057, 6905, 1100, 10616, 10628, 5051, 1582, 65535, 105, 22222, 30000, 113, 1755, 407, 1434, 2049, 689, 3128, 20222, 20034, 7580, 7579, 38080, 12401, 910, 912, 11234, 46823, 5061, 5060, 2380, 69, 5800, 62514, 42, 5631, 902, 5985, 5986, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 47001, 523, 3500, 6379, 8834
PORTS => 5671, 50000, 21, 1720, 80, 443, 143, 623, 3306, 110, 5432, 25, 22, , 23, 1521, 50013, 161, 2222, 17185, 135, 8080, 4848, 1433, 5560, 512, 513, 514, 445, 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909, 5038, 111, 139, 49, 515, 7787, 2947, 7144, 9080, 8812, 2525, 2207, 3050, 5405, 1723, 1099, 5555, 921, 10001, 123, 3690, 548, 617, 6112, 6667, 3632, 783, 10050, 38292, 12174, 2967, 5168, 3628, 7777, 6101, 10000, 6504, 41523, 41524, 2000, 1900, 10202, 6503, 6070, 6502, 6050, 2103, 41025, 44334, 2100, 5554, 12203, 26000, 4000, 1000, 8014, 5250, 34443, 8028, 8008, 7510, 9495, 1581, 8000, 18881, 57772, 9090, 9999, 81, 3000, 8300, 8800, 8090, 389, 10203, 5093, 1533, 13500, 705, 4659, 20031, 16102, 6080, 6660, 11000, 19810, 3057, 6905, 1100, 10616, 10628, 5051, 1582, 65535, 105, 22222, 30000, 113, 1755, 407, 1434, 2049, 689, 3128, 20222, 20034, 7580, 7579, 38080, 12401, 910, 912, 11234, 46823, 5061, 5060, 2380, 69, 5800, 62514, 42, 5631, 902, 5985, 5986, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 47001, 523, 3500, 6379, 8834
msf6 auxiliary(scanner/portscan/tcp) > run -j
[-] Auxiliary failed: NoMethodError undefined method `prompting' for #<Msf::Ui::Web::WebConsole::WebConsolePipe:0x00007f525ceb10f8 @subscribers_out={"msfweb"=>#<Rex::Ui::Text::Output::Buffer:0x00007f525ceb40a0 @buf="">}, @subscribers_ref={}, @subscribers_idx=0, @pipe_input=#<Rex::Ui::Text::Input::Buffer:0x00007f525ceb0f18 @sock=#<Rex::Ui::Text::Input::Buffer::BufferSock:0x00007f525ceb0db0 @lsock=#<TCPSocket:fd 30, AF_INET, 127.0.0.1, 35905>, @rsock=#<TCPSocket:fd 29, AF_INET, 127.0.0.1, 57092>>>, @output=#<Msf::Ui::Web::WebConsole::WebConsolePipe:0x00007f525ceb10f8 ...>, @input=nil, @prompt="msf6 auxiliary(scanner/portscan/tcp) > ">
Did you mean?  prompting?
               prompt
               prompt=
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:280:in `ensure in without_prompt'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:280:in `without_prompt'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/alert.rb:245:in `alert_user'
[-]   /usr/share/metasploit-framework/lib/msf/core/module/ui.rb:21:in `init_ui'

**Comment by mosesmbadi** [comment] 2024-03-16 22:32
> This should be fixed in the latest version of Metasploit

I'm also stuck on this issue. What do you mean by latest version? I'm using v6.3.55-dev. 
The exact output of `msfconsole --version`  is `Framework Version: 6.3.55-dev`. 
Is there a more recent version? I 'm using metasploit that came pre-built in Kali-linux/Rolling vagrant image.

**Comment by nrathaus** [comment] 2024-04-05 15:26
Latest version at the moment is `6.4.1-dev-` and it works for me:
```
msf6 auxiliary(scanner/portscan/tcp) > set PORTS 5671, 50000, 21, 1720, 80, 443, 143, 623, 3306, 110, 5432, 25, 22, , 23, 1521, 50013, 161, 2222, 17185, 135, 8080, 4848, 1433, 5560, 512, 513, 514, 445, 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909, 5038, 111, 139, 49, 515, 7787, 2947, 7144, 9080, 8812, 2525, 2207, 3050, 5405, 1723, 1099, 5555, 921, 10001, 123, 3690, 548, 617, 6112, 6667, 3632, 783, 10050, 38292, 12174, 2967, 5168, 3628, 7777, 6101, 10000, 6504, 41523, 41524, 2000, 1900, 10202, 6503, 6070, 6502, 6050, 2103, 41025, 44334, 2100, 5554, 12203, 26000, 4000, 1000, 8014, 5250, 34443, 8028, 8008, 7510, 9495, 1581, 8000, 18881, 57772, 9090, 9999, 81, 3000, 8300, 8800, 8090, 389, 10203, 5093, 1533, 13500, 705, 4659, 20031, 16102, 6080, 6660, 11000, 19810, 3057, 6905, 1100, 10616, 10628, 5051, 1582, 65535, 105, 22222, 30000, 113, 1755, 407, 1434, 2049, 689, 3128, 20222, 20034, 7580, 7579, 38080, 12401, 910, 912, 11234, 46823, 5061, 5060, 2380, 69, 5800, 62514, 42, 5631, 902, 5985, 5986, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 47001, 523, 3500, 6379, 8834
PORTS => 5671, 50000, 21, 1720, 80, 443, 143, 623, 3306, 110, 5432, 25, 22, , 23, 1521, 50013, 161, 2222, 17185, 135, 8080, 4848, 1433, 5560, 512, 513, 514, 445, 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909, 5038, 111, 139, 49, 515, 7787, 2947, 7144, 9080, 8812, 2525, 2207, 3050, 5405, 1723, 1099, 5555, 921, 10001, 123, 3690, 548, 617, 6112, 6667, 3632, 783, 10050, 38292, 12174, 2967, 5168, 3628, 7777, 6101, 10000, 6504, 41523, 41524, 2000, 1900, 10202, 6503, 6070, 6502, 6050, 2103, 41025, 44334, 2100, 5554, 12203, 26000, 4000, 1000, 8014, 5250, 34443, 8028, 8008, 7510, 9495, 1581, 8000, 18881, 57772, 9090, 9999, 81, 3000, 8300, 8800, 8090, 389, 10203, 5093, 1533, 13500, 705, 4659, 20031, 16102, 6080, 6660, 11000, 19810, 3057, 6905, 1100, 10616, 10628, 5051, 1582, 65535, 105, 22222, 30000, 113, 1755, 407, 1434, 2049, 689, 3128, 20222, 20034, 7580, 7579, 38080, 12401, 910, 912, 11234, 46823, 5061, 5060, 2380, 69, 5800, 62514, 42, 5631, 902, 5985, 5986, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 47001, 523, 3500, 6379, 8834
msf6 auxiliary(scanner/portscan/tcp) > 
msf6 auxiliary(scanner/portscan/tcp) > set RHOSTS 127.0.0.1
msf6 auxiliary(scanner/portscan/tcp) > run -j
msf6 auxiliary(scanner/portscan/tcp) > 
[+] 127.0.0.1:            - 127.0.0.1:3306 - TCP OPEN
[*] 127.0.0.1:            - Scanned 1 of 1 hosts (100% complete)
```

**Comment by adfoster-r7** [comment] 2024-04-05 15:41
Confirmed as working on the latest version of Metasploit - 6.4.0+

Closing :+1:

**Closed by adfoster-r7** 2024-04-05 15:41 UTC
Labels: bug

**Comment by nonamebaby23** [comment] 2024-05-08 20:34
why prompting error is shown in armitage

**Comment by adfoster-r7** [comment] 2024-05-08 20:50
Update your Metasploit framework version, or create a new issue :+1:

**Comment by nonamebaby23** [comment] 2024-05-08 21:27
msf6 > db_nmap --min-hostgroup 96 -T4 -A -v -n 45.66.35.21 
[-] Database not connected


I have updated my msf but while doing nmap scan, i am getting this in armitage

**Comment by adfoster-r7** [comment] 2024-05-08 21:56
Please raise a new issue, and ensure all the information is provided in the issue template - thanks!
